// REFACTORED: CP-JAVA11
/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.04.26 at 01:35:31 PM ACT
//

package com.percussion.dashboardmanagement.data;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.xml.bind.annotation.*;

/** Java class for DashboardContent JAXB mapping. */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"gadgetDef"})
@XmlRootElement(name = "DashboardContent")
public class DashboardContent {

  @XmlElement(name = "GadgetDef", required = true)
  protected List<DashboardContent.GadgetDef> gadgetDef;

  /**
   * Gets the value of the gadgetDef property. This accessor method returns a reference to the live
   * list, not a snapshot. Therefore any modification you make to the returned list will be present
   * inside the JAXB object.
   */
  public List<DashboardContent.GadgetDef> getGadgetDef() {
    if (gadgetDef == null) {
      gadgetDef = new ArrayList<>();
    }
    return this.gadgetDef;
  }

  /** Java class for GadgetDef JAXB mapping. */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"userPref"})
  public static class GadgetDef {

    @XmlElement(name = "UserPref")
    protected List<DashboardContent.GadgetDef.UserPref> userPref;

    @XmlAttribute(required = true)
    protected String gadgetType;

    @XmlAttribute protected Boolean expanded;

    @XmlAttribute(required = true)
    protected int column;

    /**
     * Gets the value of the userPref property. This accessor method returns a reference to the live
     * list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object.
     */
    public List<DashboardContent.GadgetDef.UserPref> getUserPref() {
      if (userPref == null) {
        userPref = new ArrayList<>();
      }
      return this.userPref;
    }

    public String getGadgetType() {
      return gadgetType;
    }

    public void setGadgetType(String value) {
      this.gadgetType = value;
    }

    public boolean isExpanded() {
      return Optional.ofNullable(expanded).orElse(true);
    }

    public void setExpanded(Boolean value) {
      this.expanded = value;
    }

    public int getColumn() {
      return column;
    }

    public void setColumn(int value) {
      this.column = value;
    }

    /** Java class for UserPref JAXB mapping. */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
        name = "",
        propOrder = {"value"})
    public static class UserPref {

      @XmlValue protected String value;

      @XmlAttribute(required = true)
      protected String name;

      public String getValue() {
        return value;
      }

      public void setValue(String value) {
        this.value = value;
      }

      public String getName() {
        return name;
      }

      public void setName(String value) {
        this.name = value;
      }
    }
  }
}
