// REFACTORED: CP-JAVA11
/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.26 at 01:35:31 PM ACT 
//


package com.percussion.dashboardmanagement.data;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * Factory methods for JAXB classes in com.percussion.dashboardmanagement.data.
 */
@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public DashboardContent.GadgetDef.UserPref createDashboardContentGadgetDefUserPref() {
        return new DashboardContent.GadgetDef.UserPref();
    }

    public DashboardContent createDashboardContent() {
        return new DashboardContent();
    }

    public DashboardContent.GadgetDef createDashboardContentGadgetDef() {
        return new DashboardContent.GadgetDef();
    }
}
