/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.percussion.services.workflow;

import com.percussion.error.IPSErrorCode;
import com.percussion.utils.exceptions.PSBaseException;
import com.percussion.utils.guid.IPSGuid;

import java.util.Objects;
import java.util.Optional;
import com.intsof.percussioncms.auditlog.codes.WorkflowErrorCodes;

/**
 * Exceptions generated by the workflow service with Java 11 modernization.
 * This exception provides specific error handling for workflow service operations
 * with enhanced factory methods and null-safe operations.
 *
 * <h2>Java 11 Features</h2>
 * <ul>
 * <li>Factory methods for common error scenarios</li>
 * <li>Enhanced validation with Objects.requireNonNull</li>
 * <li>Optional-based safe access to error context</li>
 * <li>Immutable error details</li>
 * </ul>
 *
 * @author dougrand
 */
public class PSWorkflowException extends PSBaseException {

    /**
     * Serial version UID for serialization compatibility.
     */
    private static final long serialVersionUID = 4181855115204766647L;

    /**
     * Optional workflow ID associated with this exception.
     */
    private final IPSGuid workflowId;

    /**
     * Optional state ID associated with this exception.
     */
    private final IPSGuid stateId;

    /**
     * Construct a workflow exception for messages taking an array of
     * arguments. Be sure to store the arguments in the correct order in
     * the array, where {0} in the string is array element 0, etc.
     *
     * @param msgCode The code of the error string to load.
     * @param arrayArgs The array of arguments to use as the arguments
     *    in the error message. May be {@code null}, and may contain
     *    {@code null} elements.
     */
    public PSWorkflowException(int msgCode, Object... arrayArgs) {
        super(msgCode, arrayArgs);
        this.workflowId = null;
        this.stateId = null;
    }

    /**
     * Same as {@link #PSWorkflowException(int, Object...)} but takes one
     * additional parameter to indicate the exception that caused this exception.
     *
     * @param msgCode The code of the error string to load.
     * @param cause The original exception that caused this exception to be
     *           thrown, may be {@code null}.
     * @param arrayArgs The array of arguments to use as the arguments in the
     *           error message. May be {@code null}, and may contain
     *           {@code null} elements.
     */
    public PSWorkflowException(int msgCode, Throwable cause, Object... arrayArgs) {
        super(msgCode, cause, arrayArgs);
        this.workflowId = null;
        this.stateId = null;
    }

    /**
     * Construct a workflow exception for messages taking no arguments.
     *
     * @param msgCode The error string to load.
     */
    public PSWorkflowException(int msgCode) {
        super(msgCode);
        this.workflowId = null;
        this.stateId = null;
    }

    /**
     * Typed construction from a catalogued {@link IPSErrorCode}.
     *
     * @param code catalogued error code, never {@code null}
     * @param arrayArgs the array of arguments to use as the arguments in the error message
     */
    public PSWorkflowException(IPSErrorCode code, Object... arrayArgs) {
        super(code, arrayArgs);
        this.workflowId = null;
        this.stateId = null;
    }

    /**
     * Typed construction with a cause.
     *
     * @param code catalogued error code, never {@code null}
     * @param cause the original exception, may be {@code null}
     * @param arrayArgs the array of arguments to use as the arguments in the error message
     */
    public PSWorkflowException(IPSErrorCode code, Throwable cause, Object... arrayArgs) {
        super(code, cause, arrayArgs);
        this.workflowId = null;
        this.stateId = null;
    }

    /**
     * Private constructor for factory methods with workflow context.
     *
     * @param msgCode The code of the error string to load.
     * @param cause The original exception, may be {@code null}
     * @param workflowId The workflow ID context, may be {@code null}
     * @param stateId The state ID context, may be {@code null}
     * @param arrayArgs The array of arguments for the error message
     */
    private PSWorkflowException(int msgCode, Throwable cause, IPSGuid workflowId,
                               IPSGuid stateId, Object... arrayArgs) {
        super(msgCode, cause, arrayArgs);
        this.workflowId = workflowId;
        this.stateId = stateId;
    }

    private PSWorkflowException(IPSErrorCode code, Throwable cause, IPSGuid workflowId,
                               IPSGuid stateId, Object... arrayArgs) {
        super(code, cause, arrayArgs);
        this.workflowId = workflowId;
        this.stateId = stateId;
    }

    /**
     * Factory method for workflow not found errors.
     *
     * @param workflowId the workflow ID that was not found, not {@code null}
     * @return a new PSWorkflowException instance
     * @throws IllegalArgumentException if workflowId is null
     */
    public static PSWorkflowException workflowNotFound(IPSGuid workflowId) {
        Objects.requireNonNull(workflowId, "workflowId cannot be null");
        return new PSWorkflowException(WorkflowErrorCodes.WORKFLOW_NOT_FOUND, null,
                                     workflowId, null, workflowId);
    }

    /**
     * Factory method for workflow state not found errors.
     *
     * @param stateId the state ID that was not found, not {@code null}
     * @param workflowId the workflow ID context, not {@code null}
     * @return a new PSWorkflowException instance
     * @throws IllegalArgumentException if stateId or workflowId is null
     */
    public static PSWorkflowException stateNotFound(IPSGuid stateId, IPSGuid workflowId) {
        Objects.requireNonNull(stateId, "stateId cannot be null");
        Objects.requireNonNull(workflowId, "workflowId cannot be null");
        return new PSWorkflowException(WorkflowErrorCodes.STATE_NOT_FOUND, null,
                                     workflowId, stateId, stateId, workflowId);
    }

    /**
     * Factory method for invalid workflow state errors.
     *
     * @param stateId the invalid state ID, not {@code null}
     * @param workflowId the workflow ID context, not {@code null}
     * @param reason the reason for invalidity, may be {@code null}
     * @return a new PSWorkflowException instance
     * @throws IllegalArgumentException if stateId or workflowId is null
     */
    public static PSWorkflowException invalidState(IPSGuid stateId, IPSGuid workflowId, String reason) {
        Objects.requireNonNull(stateId, "stateId cannot be null");
        Objects.requireNonNull(workflowId, "workflowId cannot be null");
        var reasonText = reason != null ? reason : "Unknown reason";
        return new PSWorkflowException(WorkflowErrorCodes.INVALID_STATE, null,
                                     workflowId, stateId, stateId, workflowId, reasonText);
    }

    /**
     * Factory method for workflow operation errors with cause.
     *
     * @param operation the operation that failed, not {@code null}
     * @param cause the underlying cause, not {@code null}
     * @param workflowId the workflow ID context, may be {@code null}
     * @return a new PSWorkflowException instance
     * @throws IllegalArgumentException if operation or cause is null
     */
    public static PSWorkflowException operationFailed(String operation, Throwable cause, IPSGuid workflowId) {
        Objects.requireNonNull(operation, "operation cannot be null");
        Objects.requireNonNull(cause, "cause cannot be null");
        return new PSWorkflowException(WorkflowErrorCodes.OPERATION_FAILED, cause,
                                     workflowId, null, operation, cause.getMessage());
    }

    /**
     * Factory method for workflow validation errors.
     *
     * @param workflowId the workflow ID being validated, not {@code null}
     * @param validationMessage the validation error message, not {@code null}
     * @return a new PSWorkflowException instance
     * @throws IllegalArgumentException if workflowId or validationMessage is null
     */
    public static PSWorkflowException validationFailed(IPSGuid workflowId, String validationMessage) {
        Objects.requireNonNull(workflowId, "workflowId cannot be null");
        Objects.requireNonNull(validationMessage, "validationMessage cannot be null");
        return new PSWorkflowException(WorkflowErrorCodes.VALIDATION_FAILED, null,
                                     workflowId, null, workflowId, validationMessage);
    }

    /**
     * Factory method for unauthorized workflow access errors.
     *
     * @param workflowId the workflow ID that access was denied to, not {@code null}
     * @param userName the user attempting access, may be {@code null}
     * @return a new PSWorkflowException instance
     * @throws IllegalArgumentException if workflowId is null
     */
    public static PSWorkflowException accessDenied(IPSGuid workflowId, String userName) {
        Objects.requireNonNull(workflowId, "workflowId cannot be null");
        var user = userName != null ? userName : "Unknown user";
        return new PSWorkflowException(WorkflowErrorCodes.ACCESS_DENIED, null,
                                     workflowId, null, workflowId, user);
    }

    /**
     * Get the workflow ID associated with this exception.
     *
     * @return an Optional containing the workflow ID if available, empty otherwise
     */
    public Optional<IPSGuid> getWorkflowId() {
        return Optional.ofNullable(workflowId);
    }

    /**
     * Get the state ID associated with this exception.
     *
     * @return an Optional containing the state ID if available, empty otherwise
     */
    public Optional<IPSGuid> getStateId() {
        return Optional.ofNullable(stateId);
    }

    /**
     * Check if this exception has workflow context.
     *
     * @return {@code true} if workflow ID is available, {@code false} otherwise
     */
    public boolean hasWorkflowContext() {
        return workflowId != null;
    }

    /**
     * Check if this exception has state context.
     *
     * @return {@code true} if state ID is available, {@code false} otherwise
     */
    public boolean hasStateContext() {
        return stateId != null;
    }

    /**
     * Get a formatted error context string including workflow and state IDs if available.
     *
     * @return a formatted context string, never {@code null}
     */
    public String getErrorContext() {
        var context = new StringBuilder();
        if (workflowId != null) {
            context.append("Workflow ID: ").append(workflowId);
        }
        if (stateId != null) {
            if (context.length() > 0) {
                context.append(", ");
            }
            context.append("State ID: ").append(stateId);
        }
        return context.length() > 0 ? context.toString() : "No context available";
    }

    @Override
    protected String getResourceBundleBaseName() {
        return "com.percussion.services.workflow.PSWorkflowErrorStringBundle";
    }

    @Override
    public String toString() {
        var baseString = super.toString();
        var context = getErrorContext();
        return context.equals("No context available") ? baseString : baseString + " [" + context + "]";
    }
}
