<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:atom="http://www.w3.org/2005/Atom"
           targetNamespace="http://www.w3.org/2005/Atom"
           elementFormDefault="qualified">

    <xs:element name="feed">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="subtitle" type="xs:string" minOccurs="0"/>
                <xs:element name="link" type="linkType" maxOccurs="unbounded"/>
                <xs:element name="updated" type="xs:dateTime"/>
                <xs:element name="author" type="personType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="id" type="xs:string"/>
                <xs:element name="entry" type="entryType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="personType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="email" type="xs:string" minOccurs="0"/>
            <xs:element name="uri" type="xs:anyURI" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="linkType">
        <xs:attribute name="href" type="xs:anyURI" use="required"/>
        <xs:attribute name="rel" type="xs:string" use="optional"/>
        <xs:attribute name="type" type="xs:string" use="optional"/>
        <xs:attribute name="hreflang" type="xs:language" use="optional"/>
        <xs:attribute name="title" type="xs:string" use="optional"/>
        <xs:attribute name="length" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>

    <xs:complexType name="entryType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="link" type="linkType" maxOccurs="unbounded"/>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="updated" type="xs:dateTime"/>
            <xs:element name="published" type="xs:dateTime" minOccurs="0"/>
            <xs:element name="author" type="personType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="summary" type="contentType" minOccurs="0"/>
            <xs:element name="content" type="contentType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="contentType" mixed="true">
        <xs:sequence>
            <xs:any namespace="##any" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="optional"/>
        <xs:attribute name="src" type="xs:anyURI" use="optional"/>
    </xs:complexType>
</xs:schema>
