<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.percussion</groupId>
        <artifactId>core</artifactId>
        <version>8.1.6</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <artifactId>perc-packages</artifactId>
    <properties>
        <REFRESH_PROP_NAME>REFRESH</REFRESH_PROP_NAME>
        <assembly-directory>${basedir}/target/distribution</assembly-directory>
        <db.backend>DERBY</db.backend>
        <db.class>org.apache.derby.jdbc.EmbeddedDriver</db.class>
        <db.driver>derby</db.driver>
        <db.name/>
        <db.pass.enc>7cf3be70d83a6948</db.pass.enc>
        <db.schema>CMDB</db.schema>
        <db.server>CMDB;create=true</db.server>
        <db.user>CMDB</db.user>
        <derby-home>${basedir}/target/derby-home</derby-home>
        <ds.name>PercussionData</ds.name>
        <exts.store>${basedir}/target/distribution/Extensions</exts.store>
        <jetty-directory>${basedir}/target/jetty</jetty-directory>
        <pkg.tmp.dir>${basedir}/target/distribution/Packages</pkg.tmp.dir>
        <rxapps-directory>${basedir}/target/rxapps</rxapps-directory>
    </properties>
    <dependencies/>
    <build>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <version>1.2.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>set-system-properties</goal>
                        </goals>
                        <configuration>
                            <properties>
                                <property>
                                    <name>derby.system.home</name>
                                    <value>${derby-home}</value>
                                </property>
                            </properties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${maven.antrun.plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>com.percussion</groupId>
                        <artifactId>perc-ant</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>populate-perc-distribution-with-packages</id>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <target>
                                <property name="plugin_classpath" refid="maven.plugin.classpath"/>
                                <taskdef loaderref="perc.loader" resource="com/percussion/ant/antlib.xml"/>
                                <taskdef loaderref="perc.loader" resource="net/sf/antcontrib/antlib.xml"/>
                                <ant antfile="${basedir}/packages-ant.xml" inheritRefs="true">
                                    <property name="plugin_classpath" refid="maven.plugin.classpath"/>
                                </ant>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>${maven.assembly.plugin.version}</version>
                <configuration>
                    <descriptors>
                        <descriptor>src/main/assembly/perc-assembly.xml</descriptor>
                    </descriptors>
                    <tarLongFileMode>posix</tarLongFileMode>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
