#!/usr/bin/env bash
# scripts/release-audit/lib/backlog.sh
# User Story 3 — migration backlog generator.
# Source from release-audit.sh; depends on lib/common.sh being sourced first.

# Priority constants
readonly PRIORITY_P0="P0"   # Security
readonly PRIORITY_P1="P1"   # REST contract / Publishing
readonly PRIORITY_P2="P2"   # UI fix
readonly PRIORITY_P3="P3"   # Cosmetic / Gadget

# classify_priority <prrecord-json>
# Echoes a priority string.
classify_priority() {
  local pr="$1"
  local sec
  sec="$(jq -r '.securityFlag // false' <<<"${pr}")"
  if [[ "${sec}" == "true" ]]; then
    printf '%s\n' "${PRIORITY_P0}"
    return
  fi
  # P1 if any modulePath matches REST / publishing / sitemanage
  local modules
  modules="$(jq -r '.modulePaths // [] | join(" ")' <<<"${pr}")"
  if [[ "${modules}" =~ rest ]] || [[ "${modules}" =~ sitemanage ]] || [[ "${modules}" =~ publishing ]]; then
    printf '%s\n' "${PRIORITY_P1}"
    return
  fi
  # P2 if any modulePath matches WebUI / widgets / gadgets
  if [[ "${modules}" =~ WebUI ]] || [[ "${modules}" =~ widget ]] || [[ "${modules}" =~ gadget ]]; then
    printf '%s\n' "${PRIORITY_P2}"
    return
  fi
  printf '%s\n' "${PRIORITY_P3}"
}

# recommend_strategy <prrecord-json> <verdict-json>
# Echoes one of: cherry-pick, back-port, re-implement, skip
recommend_strategy() {
  local pr="$1"
  local vj="$2"
  local jdk8
  jdk8="$(jq -r '.jdk8OnlyFlag // false' <<<"${pr}")"
  if [[ "${jdk8}" == "true" ]]; then
    printf '%s\n' "back-port"
    return
  fi
  # Default
  printf '%s\n' "cherry-pick"
}

# generate_backlog <output-dir>
# Reads inventory.json and verdicts.json; emits migration-backlog.md.
run_backlog_phase() {
  local output_dir="$1"
  local inventory="${output_dir}/inventory.json"
  local verdicts="${output_dir}/verdicts.json"
  local backlog="${output_dir}/migration-backlog.md"
  local config="${output_dir}/_audit_config.json"

  log_info "generating migration-backlog.md"

  # Build a join of inventory + verdicts, then filter to needs-migration only
  jq -s '
    .[0] as $inv
    | .[1] as $verd
    | [
        $inv[] as $pr
        | ($verd | map(select(.prNumber == $pr.number)) | .[0]) as $v
        | {
            number: $pr.number,
            title: $pr.title,
            mergedAt: $pr.mergedAt,
            mergeCommitSha: $pr.mergeCommitSha,
            author: $pr.author,
            modulePaths: ($pr.modulePaths // []),
            jdk8OnlyFlag: ($pr.jdk8OnlyFlag // false),
            securityFlag: (($v.securityFlag // false) or ($pr.securityFlag // false)),
            verdict: ($v.verdict // "needs-migration"),
            evidenceCommit: ($v.evidenceCommit // ""),
            evidenceFilePath: ($v.evidenceFilePath // ""),
            evidenceNote: ($v.evidenceNote // "")
          }
      ]
    | map(select(.verdict == "needs-migration"))
  ' "${inventory}" "${verdicts}" > "${output_dir}/_backlog_candidates.json"

  local total
  total="$(jq 'length' "${output_dir}/_backlog_candidates.json")"
  log_info "backlog candidates: ${total}"

  # Compute top matter
  local from_tag to_tag target_branch
  from_tag="$(jq -r '.fromTag' "${config}")"
  to_tag="$(jq -r '.toTag' "${config}")"
  target_branch="$(jq -r '.targetBranch' "${config}")"
  local run_ts
  run_ts="$(jq -r '.runTimestamp' "${config}")"

  # Header
  {
    printf '# Migration Backlog: %s → %s\n\n' "${from_tag}" "${to_tag}"
    printf '**Tag range**: `%s..%s`  \n' "${from_tag}" "${to_tag}"
    printf '**Target branch**: `%s`  \n' "${target_branch}"
    printf '**Run timestamp**: %s  \n' "${run_ts}"
    printf '**Total backlog items**: %s  \n' "${total}"
    printf '\n> Generated by `scripts/release-audit/release-audit.sh`. Each row is one v8.1.7 PR with verdict `needs-migration` against `%s`.\n\n' "${target_branch}"
  } > "${backlog}"

  # Emit per-priority sections
  for prio in P0 P1 P2 P3; do
    case "${prio}" in
      P0) section="P0 — Security" ;;
      P1) section="P1 — REST contract / Publishing" ;;
      P2) section="P2 — UI fix" ;;
      P3) section="P3 — Cosmetic / Gadget" ;;
    esac

    # Filter candidates to this priority
    jq --arg prio "${prio}" '
      [
        .[] | {
          pr: .,
          prio: (
            if .securityFlag then "P0"
            elif ((.modulePaths // []) | any(. == "rest" or (. | startswith("projects/sitemanage")) or (. | startswith("deliverytiersuite/delivery-tier-suite")))) then "P1"
            elif ((.modulePaths // []) | any(. | startswith("WebUI"))) then "P2"
            else "P3"
            end
          )
        }
      ] | map(select(.prio == $prio))
    ' "${output_dir}/_backlog_candidates.json" > "${output_dir}/_backlog_${prio}.json"

    local prio_count
    prio_count="$(jq 'length' "${output_dir}/_backlog_${prio}.json")"

    {
      printf '## %s\n\n' "${section}"
      if [[ "${prio_count}" -eq 0 ]]; then
        printf '_No items at this priority._\n\n'
      else
        printf '| PR | Title | Module | Strategy | Test coverage in v8.1.7 | Blockers |\n'
        printf '|----|-------|--------|----------|------------------------|----------|\n'
        jq -r '.[] | .pr | "| [#\(.number)](https://github.com/intersoftdatalabs-in/percussioncms/pull/\(.number)) | \(.title[0:80]) | \((.modulePaths // ["(none)"])[0]) | cherry-pick | _see v8.1.7 PR_ |  |"' "${output_dir}/_backlog_${prio}.json"
      fi
      printf '\n'
    } >> "${backlog}"
  done

  # Issue clusters appendix (per FR-005a): group PRs by GitHub issue number
  # referenced in PR titles. Pattern: "#NNN" or "GH-NNN" or "issue NNN".
  {
    printf '## Issue Clusters Appendix\n\n'
    printf 'PRs grouped by GitHub issue reference extracted from titles.\n\n'
    printf '| Issue | PRs | Recommendation |\n'
    printf '|-------|-----|----------------|\n'
    # For each needs-migration PR, extract the first issue number from title
    jq -r '
      .[]
      | (.title | capture("(?<i>(?:#|GH-|issue )(?<n>[0-9]+))")? | .n) as $iss
      | select($iss != null)
      | "\($iss)\t\(.number)\t\(.title[0:60])"
    ' "${output_dir}/_backlog_candidates.json" \
      | sort -n \
      | awk -F'\t' '
          { if ($1 != prev) {
              if (prev != "") printf "| #%s | %s | _recommend latest merge_ |\n", prev, prs
              prev=$1; prs="["$2"]("$2")"
            } else { prs = prs", ["$2"]("$2")" }
          }
          END { if (prev != "") printf "| #%s | %s | _recommend latest merge_ |\n", prev, prs }
        ' >> "${backlog}"
    printf '\n'
  } >> "${backlog}"

  # Cleanup
  rm -f "${output_dir}/_backlog_candidates.json" "${output_dir}/_backlog_"*.json

  log_info "backlog written: ${backlog}"
}