version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "development-8.1.x"
    # ignore known groups/artifacts that require > Java 1.8.0+
    ignore:
      - dependency-name: "org.apache.cxf:*"
        versions:
          - ">=3.6.0"
      - dependency-name: "org.basepom.maven:duplicate-finder-maven-plugin"
        versions:
          - ">=2.0.0"
      - dependency-name: "org.quartz-scheduler:quartz"
        versions:
          - ">=2.5.0"
      - dependency-name: "org.springframework:*"
        versions:
          - ">=6.0.0"
      - dependency-name: "org.apache.tika:*"
        versions:
          - ">=3.0.0"
      - dependency-name: "org.junit.jupiter:*"
        versions:
          - ">=6.0.0"
      - dependency-name: "org.apache.activemq:*"
        versions:
          - ">=5.17.0"
      - dependency-name: "org.jboss.logging:jboss-logging"
        versions:
          - ">=3.5.0"
      - dependency-name: "org.apache.derby:*"
        versions:
          - ">=10.15.0.0"
      - dependency-name: "org.aspectj:*"
        versions:
          - ">=1.9.8"
      - dependency-name: "org.apache.myfaces.core:*"
        versions:
          - ">=4.0.0"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "development"
