- Name: 3copyobjectstore
  Class : com.percussion.service.conf.tasks.impl.PSConfigTaskFileCopy
  RunFrequency: ON_CONTAINER_REFRESH
  RunAtState: BEFORE_CM1_STARTUP
  RunInEnv :
     - DOCKER
  Parameters:
    Action: copy
    Type: directory
    Source: var/ObjectStore
    Destination: ObjectStore
    PreserveFileDate: true
    FailOnSourceNotFound: false