<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.percussion</groupId>
    <artifactId>core</artifactId>
    <version>8.1.6-SNAPSHOT</version>
    <packaging>pom</packaging>
    <url>https://www.github.com/intersoftdatalabs-in/percussioncms</url>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:https://github.com/intersoftdatalabs-in/percussioncms</connection>
        <developerConnection>scm:git:https://github.com/intersoftdatalabs-in/percussioncms</developerConnection>
        <url>https://github.com/intersoftdatalabs-in/percussioncms</url>
      <tag>HEAD</tag>
  </scm>

    <modules>
        <module>modules/perc-security-utils</module>
        <module>modules/perc-security-acl-shim</module>
        <module>modules/perc-xml-security</module>
        <module>modules/perc-exceptions-spring</module>
        <module>modules/shindig-uber</module>
        <module>modules/perc-tinymce</module>
        <module>modules/utils</module>
        <module>modules/perc-legacy</module>
        <module>modules/perc-i18n</module>
        <module>modules/perc-shared-test-resources</module>
        <!-- <module>modules/webservices</module> -->
        <module>modules/Simple</module>
        <module>modules/TableFactory</module>
        <module>modules/perc-service-wrapper</module>
        <module>rest</module>
        <module>system</module>
        <module>deployer</module>
        <module>modules/Help</module>
        <module>modules/ContentUI</module>
        <module>modules/ServerUIComponents</module>
        <module>modules/extensions-default-template</module>
        <module>modules/extensions-main</module>
        <module>modules/extensions-nav</module>
        <module>modules/extensions-sfp</module>
        <module>modules/extensions-workflow</module>
        <module>modules/extensions-linkback</module>
        <module>modules/extensions-serverutils</module>
        <module>PCM-PkgMgtUI</module>
        <module>WebUI</module>
        <module>delivery</module>
        <module>projects/sitemanage</module>
        <module>modules/servletutils</module>
        <module>modules/perc-rxapps</module>
        <module>modules/perc-checkboxtree</module>
        <!-- <module>modules/DesktopContentExplorer</module> -->
        <module>modules/perc-jetty</module>
		<module>modules/perc-jetty-jars</module>
        <module>modules/perc-jetty-logging</module>
        <module>deliverytiersuite/delivery-tier-suite</module>
        <module>modules/perc-packages</module>
        <module>modules/perc-ant</module>
        <module>modules/perc-thumbnail</module>
        <module>modules/SSLTools</module>
        <module>modules/tlsutils</module>
        <module>modules/perc-toolkit</module>
        <module>modules/perc-taxonomy</module>
        <module>modules/perc-distribution-tree</module>
        <module>modules/CMLight-Main-cactus-tests</module>
        <!-- Temporarily disable missing modules to unblock reactor -->
        <!-- <module>jcadf-master</module> -->
        <!-- <module>perc-auditlog</module> -->
    </modules>
   <properties>
       <build.profile.id>dev</build.profile.id>
       <versionString>INTERNAL</versionString>
        <jenkins.buildNumber>2024</jenkins.buildNumber>
       <maven.build.timestamp.format>yyyyMMdd</maven.build.timestamp.format>
       <buildNumber>${maven.build.timestamp}</buildNumber>
       <jdk.version>11</jdk.version>
       <java.source.version>11</java.source.version>
       <java.version>11</java.version>
       <maven.compiler.source>11</maven.compiler.source>
       <maven.compiler.target>11</maven.compiler.target>
       <slf4j.version>1.7.36</slf4j.version>
       <fop.version>2.2</fop.version>
       <avalon.version>4.1.5</avalon.version>
       <maven.version>[3.6.0,)</maven.version>
       <maven.toolchains.plugin.version>3.0.0</maven.toolchains.plugin.version>
       <versions.maven.plugin.version>2.7</versions.maven.plugin.version>
       <maven.dependency.plugin.version>3.1.2</maven.dependency.plugin.version>
       <maven.surefire.plugin.version>3.2.5</maven.surefire.plugin.version>
       <maven.deploy.plugin.version>3.0.0-M1</maven.deploy.plugin.version>
       <maven.jdeps.plugin.version>3.1.2</maven.jdeps.plugin.version>
       <jdeps.fail.build>false</jdeps.fail.build>
       <jasypt.version>1.9.3</jasypt.version>
       <commons.math.version>3.6.1</commons.math.version>
       <maven.bundle.plugin.version>4.2.1</maven.bundle.plugin.version>
       <duplicate.finder.maven.plugin.version>1.4.0</duplicate.finder.maven.plugin.version>
       <maven.enforcer.plugin.version>3.0.0-M3</maven.enforcer.plugin.version>
       <maven.assembly.plugin.version>3.2.0</maven.assembly.plugin.version>
       <gwt.maven.plugin.version>2.8.2</gwt.maven.plugin.version>
       <build.helper.maven.plugin.version>3.0.0</build.helper.maven.plugin.version>
       <maven.compiler.plugin.version>3.11.0</maven.compiler.plugin.version>
       <maven.clean.plugin.version>3.2.0</maven.clean.plugin.version>
       <maven.build.helper.plugin.version>3.3.0</maven.build.helper.plugin.version>
       <maven.install.plugin.version>3.0.0-M1</maven.install.plugin.version>
       <maven.jarsigner.plugin.version>3.0.0</maven.jarsigner.plugin.version>
       <maven.checkstyle.plugin.version>3.1.1</maven.checkstyle.plugin.version>
       <maven.gpg.plugin.version>1.6</maven.gpg.plugin.version>
       <commons.file.upload.version>1.6.0</commons.file.upload.version>
       <commons.validator.version>1.7</commons.validator.version>
       <maven.site.plugin.version>3.8.2</maven.site.plugin.version>
       <maven.release.plugin.version>3.0.0-M1</maven.release.plugin.version>
       <maven.scm.plugin.version>1.11.2</maven.scm.plugin.version>
       <maven.jar.plugin.version>3.2.0</maven.jar.plugin.version>
       <maven.failsafe.plugin.version>3.2.5</maven.failsafe.plugin.version>
       <maven.resources.plugin.version>3.2.0</maven.resources.plugin.version>
       <maven.antrun.plugin.version>3.0.0</maven.antrun.plugin.version>
       <commons.rng.version>1.3</commons.rng.version>
       <maven.execmaven.plugin.version>1.6.0</maven.execmaven.plugin.version>
       <batik.version>1.14</batik.version>
       <maven.shade.plugin.version>3.2.1</maven.shade.plugin.version>
       <maven.pmd.plugin.version>3.13.0</maven.pmd.plugin.version>
       <maven.jxr.plugin.version>3.4.0</maven.jxr.plugin.version>
       <maven.war.plugin.version>3.3.1</maven.war.plugin.version>
       <plexus.component.metadata.version>2.1.0</plexus.component.metadata.version>
       <jetty.maven.plugin.version>9.4.54.v20240208</jetty.maven.plugin.version>
       <lifecycle.mapping.plugin>1.0.0</lifecycle.mapping.plugin>
       <skip.integration.tests>true</skip.integration.tests>
       <skip.unit.tests>false</skip.unit.tests>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <activemq.version>5.16.8</activemq.version><!-- 5.17.x and up require Java 11 -->
       <spring.version>5.3.23</spring.version>
       <hibernate.version>5.6.10.Final</hibernate.version>
       <hibernate.validator.version>6.2.3.Final</hibernate.validator.version>
       <ehcache.version>2.10.6</ehcache.version>
       <gson.version>2.8.9</gson.version>
       <cxf.version>3.5.11</cxf.version>
       <servlet.spec>4.0.1</servlet.spec>
       <javax.servlet.api.version>4.0.1</javax.servlet.api.version>
       <javax.annotation.api.version>1.3.2</javax.annotation.api.version>
       <jaxb.api.version>2.3.1</jaxb.api.version>
       <jaxb.runtime.version>2.3.3</jaxb.runtime.version>
       <activation.api.version>1.2.0</activation.api.version>
       <xmlgraphics.common.version>2.9</xmlgraphics.common.version>
       <commons.lang.version>2.6</commons.lang.version>
       <commons.lang3.version>3.18.0</commons.lang3.version>
       <commons-logging.version>1.3.5</commons-logging.version>
       <commons.io.version>2.18.0</commons.io.version>
       <commons.collections3.version>3.2.2</commons.collections3.version>
       <commons.collections4.version>4.4</commons.collections4.version>
       <lucene.version>8.7.0</lucene.version>
       <myfaces.version>1.1.8</myfaces.version>
       <simplexml.version>2.7.1</simplexml.version>
       <stax.version>1.0.1</stax.version>
        <poi.version>5.4.0</poi.version>
        <esapi.version>2.6.0.0</esapi.version>
        <esapi.encoder.version>1.2.3</esapi.encoder.version>
        <ant.version>1.10.14</ant.version>
        <ant.contrib.version>1.0b3</ant.contrib.version>
        <shindig.version>1.1-BETA5-incubating</shindig.version>
        <any23.version>2.3</any23.version>
        <owl.version>5.1.10</owl.version>
       <awssdk.version>1.12.261</awssdk.version>
        <bc.version>1.78</bc.version>
        <jackson.version>2.15.0</jackson.version>
        <jsoup.version>1.15.3</jsoup.version>
        <json.version>20240303</json.version>
        <junit5.version>5.13.1</junit5.version>
        <junit.version>4.13.1</junit.version>
        <cactus.version>13-1.7.1</cactus.version>
        <cactus.sysproperties>cactus.contextURL</cactus.sysproperties>
        <cactus.contextURL>http://localhost:9992/Rhythmyx</cactus.contextURL>
        <jetty.version>9.4.54.v20240208</jetty.version>
        <trinidad.version>1.0.2</trinidad.version>
       <derby.version>10.14.2.0</derby.version>
       <mssql.version>12.4.1.jre8</mssql.version>
       <oracle.version>12.1.0.1</oracle.version>
       <jtds.version>1.3.1</jtds.version>
       <install.jre.version>8.222.10.1</install.jre.version>       <httpcomponents.version>4.5.13</httpcomponents.version>
       <tika.version>1.28.5</tika.version>
       <commons-cli.version>1.4</commons-cli.version>
       <opencsv.version>4.6</opencsv.version>
       <xmpbox.version>2.0.17</xmpbox.version>
       <jbig2.version>3.0.2</jbig2.version>
       <pdfbox.version>2.0.24</pdfbox.version>
       <sqlite.version>3.41.2.2</sqlite.version>
       <swagger.version>2.1.10</swagger.version>
       <swagger.ui.version>3.51.2</swagger.ui.version>
       <commons.compress.version>1.26.0</commons.compress.version>
       <solr.version>8.11.3</solr.version>
        <nettyall.version>4.1.45.Final</nettyall.version>
       <hikari.version>4.0.3</hikari.version>
       <snakeyaml.version>2.0</snakeyaml.version>
       <commons-email.version>1.5</commons-email.version>
       <commons.codec.version>1.15</commons.codec.version>
       <tinymce.version>5.10.3</tinymce.version>
       <jfx.version>11.0.2</jfx.version>
       <twelvemonkeys.version>3.9.4</twelvemonkeys.version>
       <commons.beanutils.version>1.11.0</commons.beanutils.version>
       <xstream.version>1.4.21</xstream.version>
       <log4j2.version>2.18.0</log4j2.version>
       <guava.version>32.0.1-jre</guava.version>
       <xerces.version>2.12.2</xerces.version>
       <xmlresolver.version>1.2</xmlresolver.version>
       <quartz.version>2.3.2</quartz.version>
       <rome.version>1.15.0</rome.version>
       <maven.source.jar.plugin.version>3.2.0</maven.source.jar.plugin.version>
       <velocity.version>2.3</velocity.version>
       <velocity.tools.version>3.1</velocity.tools.version>
       <saxon.version>6.5.3</saxon.version>
       <owasp.csrfguard.version>4.0.0</owasp.csrfguard.version>
       <sitemap4j.version>1.1.2</sitemap4j.version>
       <eclipse-manifest-location>META-INF</eclipse-manifest-location>
       
	<!-- Centralized Jakarta Annotations API version -->
    <jakarta.annotation.api.version>2.1.1</jakarta.annotation.api.version>
    <!-- Optional: keep javax annotation property for legacy modules if referenced -->
    <javax.annotation.api.version>1.3.2</javax.annotation.api.version>
       
    <twelveMonkeys.version>3.10.1</twelveMonkeys.version>
    </properties>


    <profiles>
        <profile>
            <id>all-tests</id>
            <properties>
                <build.profile.id>all-tests</build.profile.id>
                <!-- All tests are run. -->
                <skip.integration.tests>false</skip.integration.tests>
                <skip.unit.tests>false</skip.unit.tests>
            </properties>
        </profile>
        <profile>
            <id>dev</id>
        </profile>
        <profile>
            <id>integration-test</id>
            <properties>
                <!-- Used to locate the profile specific configuration file. -->
                <build.profile.id>integration-test</build.profile.id>
                <!-- Only integration tests are run. -->
                <skip.integration.tests>false</skip.integration.tests>
                <skip.unit.tests>true</skip.unit.tests>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jarsigner-plugin</artifactId>
                <version>${maven.jarsigner.plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-scm-plugin</artifactId>
                <version>${maven.scm.plugin.version}</version>
                <configuration>
                    <connectionType>github</connectionType>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>${maven.release.plugin.version}</version>
                <configuration>
                    <pushChanges>false</pushChanges>
                    <localCheckout>true</localCheckout>
                    <tagNameFormat>v@{project.version}</tagNameFormat>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-toolchains-plugin</artifactId>
                <version>${maven.toolchains.plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>toolchain</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <toolchains>
                    </toolchains>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>${maven.site.plugin.version}</version>
            </plugin>
            <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
                <version>${maven.build.helper.plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>${maven.install.plugin.version}</version>
            </plugin>
            <plugin>
            <artifactId>maven-clean-plugin</artifactId>
            <version>${maven.clean.plugin.version}</version>
            <executions />
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${maven.dependency.plugin.version}</version>
                <executions>
                    <execution>
                        <id>analyze</id>
                        <goals>
                            <goal>analyze-only</goal>
                        </goals>
                        <configuration>
                            <failOnWarning>false</failOnWarning>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <version>${maven.jar.plugin.version}</version>
            </plugin>
            <!-- Used to find plugin updates -->
            <!-- mvn versions:display-plugin-updates
            mvn versions:display-dependency-updates -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>${versions.maven.plugin.version}</version>
                <configuration>
                    <generateBackupPoms>false</generateBackupPoms>
                </configuration>
            </plugin>
            <!-- Used for Unit Tests -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
                <configuration>
                    <skipTests>${skip.unit.tests}</skipTests>
                    <argLine>${surefireArgLine}</argLine>
                    <systemPropertyVariables>
                        <cactus.contextURL>http://localhost:9992/Rhythmyx/</cactus.contextURL>
                        <javax.xml.parsers.SAXParserFactory>com.percussion.xml.PSSaxParserFactoryImpl</javax.xml.parsers.SAXParserFactory>
                        <log4j.configurationFile>${project.build.testOutputDirectory}/log4j2-tester.xml</log4j.configurationFile>
                    </systemPropertyVariables>
                    <excludedGroups>com.percussion.utils.testing.IntegrationTest,com.percussion.utils.testing.BackloggedTest</excludedGroups>
                    <testFailureIgnore>false</testFailureIgnore>
                    <includes>
                        <include>**/*Test.java</include>
                    </includes>
                </configuration>
            </plugin>
            <!-- Modern Failsafe plugin for JUnit5 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.plugin.version}</version>
                <configuration>
                    <skipTests>${skip.integration.tests}</skipTests>
                    <argLine>${failsafeArgLine}</argLine>
                    <systemPropertyVariables>
                        <javax.xml.parsers.SAXParserFactory>com.percussion.xml.PSSaxParserFactoryImpl</javax.xml.parsers.SAXParserFactory>
                        <log4j.configurationFile>${project.build.testOutputDirectory}/log4j2-tester.xml</log4j.configurationFile>
                    </systemPropertyVariables>
                    <excludedGroups>com.percussion.utils.testing.BackloggedTest</excludedGroups>
                    <testFailureIgnore>false</testFailureIgnore>
                    <includes>
                        <include>**/*IT.java</include>
                    </includes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven.checkstyle.plugin.version}</version>
                <configuration>
                    <configLocation>google_checks.xml</configLocation>
                    <encoding>UTF-8</encoding>
                    <consoleOutput>true</consoleOutput>
                    <failsOnError>false</failsOnError>
                    <linkXRef>true</linkXRef>
                </configuration>
            </plugin>
            <!-- Used for integration tests -->
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jdeps-plugin</artifactId>
                    <version>${maven.jdeps.plugin.version}</version>
                </plugin>
                <!-- Standardize test plugins across the build -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven.surefire.plugin.version}</version>
                    <dependencies>
                        <!-- Allow running vintage JUnit 4 tests under JUnit Platform if needed -->
                        <dependency>
                            <groupId>org.junit.vintage</groupId>
                            <artifactId>junit-vintage-engine</artifactId>
                            <version>${junit5.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.junit.platform</groupId>
                            <artifactId>junit-platform-launcher</artifactId>
                            <version>${junit5.version}</version>
                        </dependency>
                    </dependencies>
                    <configuration>
                        <useModulePath>false</useModulePath>
                        <failIfNoTests>false</failIfNoTests>
                        <includes>
                            <include>**/*Test.java</include>
                        </includes>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${maven.failsafe.plugin.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.junit.vintage</groupId>
                            <artifactId>junit-vintage-engine</artifactId>
                            <version>${junit5.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.junit.platform</groupId>
                            <artifactId>junit-platform-launcher</artifactId>
                            <version>${junit5.version}</version>
                        </dependency>
                    </dependencies>
                    <configuration>
                        <useModulePath>false</useModulePath>
                        <failIfNoTests>false</failIfNoTests>
                        <includes>
                            <include>**/*IT.java</include>
                        </includes>
                    </configuration>
                </plugin>
                <plugin>
                <groupId>com.samaxes.maven</groupId>
                <artifactId>minify-maven-plugin</artifactId>
                <version>1.7.6</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.codehaus.plexus</groupId>
                            <artifactId>plexus-utils</artifactId>
                            <version>3.5.0</version>
                        </dependency>
                    </dependencies>
                </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jxr-plugin</artifactId>
                        <version>${maven.jxr.plugin.version}</version>
                    </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-gpg-plugin</artifactId>
                    <version>${maven.gpg.plugin.version}</version>
                    <executions>
                        <execution>
                            <id>sign-artifacts</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>sign</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>${maven.war.plugin.version}</version>
                </plugin>
                <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>${gwt.maven.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>${build.helper.maven.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.plexus</groupId>
                    <artifactId>plexus-component-metadata</artifactId>
                    <version>${plexus.component.metadata.version}</version>
                </plugin>
                <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven.shade.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-bundle-plugin</artifactId>
                    <version>${maven.bundle.plugin.version}</version>
                    <configuration>
                        <manifestLocation>${eclipse-manifest-location}</manifestLocation>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${maven.enforcer.plugin.version}</version>
                    <executions>
                        <execution>
                            <id>enforce</id>
                            <configuration>
                                <rules>
                                    <requirePluginVersions>
                                        <message>Best Practice is to always define plugin versions!</message>
                                    </requirePluginVersions>
                                    <requireJavaVersion>
                                        <version>${java.version}</version>
                                    </requireJavaVersion>
                                    <requireMavenVersion>
                                        <version>${maven.version}</version>
                                    </requireMavenVersion>
                                    <requireUpperBoundDeps>
                                        <excludes />
                                    </requireUpperBoundDeps>
                                    <dependencyConvergence />
                                    <banDuplicatePomDependencyVersions />
                                    <!-- Ban Jakarta servlet/annotation artifacts until full Jakarta migration -->
                                    <bannedDependencies>
                                        <excludes>
                                            <exclude>jakarta.servlet:jakarta.servlet-api</exclude>
                                            <exclude>jakarta.annotation:jakarta.annotation-api</exclude>
                                        </excludes>
                                        <searchTransitive>true</searchTransitive>
                                    </bannedDependencies>
                                </rules>
                                <fail>false</fail>
                            </configuration>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin.version}</version>
                    <configuration>
                        <source>11</source>
                        <target>11</target>
                        <!-- Consider using release instead of source/target to lock stdlib: -->
                        <!-- <release>11</release> -->
                        <fork>true</fork>
                        <debug>true</debug>
                        <debuglevel>lines,vars,source</debuglevel>
                        <meminitial>1024m</meminitial>
                        <maxmem>2024m</maxmem>
                    </configuration>
                </plugin>

                <!--This plugin's configuration is used to store Eclipse 
                    m2e settings only. It has no influence on the Maven build itself. -->
                <plugin>
                    <groupId>org.eclipse.m2e</groupId>
                    <artifactId>lifecycle-mapping</artifactId>
                    <version>${lifecycle.mapping.plugin}</version>
                    <configuration>
                        <lifecycleMappingMetadata>
                            <pluginExecutions>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>
                                            org.apache.maven.plugins
                                        </groupId>
                                        <artifactId>
                                            maven-clean-plugin
                                        </artifactId>
                                        <versionRange>
                                            [2.5,)
                                        </versionRange>
                                        <goals>
                                            <goal>clean</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore>true</ignore>
                                    </action>
                                </pluginExecution>
                            </pluginExecutions>
                        </lifecycleMappingMetadata>
                    </configuration>
                </plugin>
                <plugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-resources-plugin</artifactId>
                  <version>${maven.resources.plugin.version}</version>
                    <configuration>
                        <propertiesEncoding>ISO-8859-1</propertiesEncoding>
                    </configuration>
                </plugin>
                <plugin>
                <groupId>org.eclipse.jetty</groupId>
                  <artifactId>jetty-maven-plugin</artifactId>
                  <version>${jetty.maven.plugin.version}</version>
                <configuration>
                  <scanIntervalSeconds>10</scanIntervalSeconds>
                  <stopPort>8005</stopPort>
                  <stopKey>STOP</stopKey>
                </configuration>
              </plugin>
                <plugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-assembly-plugin</artifactId>
                  <version>${maven.assembly.plugin.version}</version>
                  <dependencies>
                    <dependency>
                      <groupId>org.eclipse.jetty.toolchain</groupId>
                      <artifactId>jetty-assembly-descriptors</artifactId>
                      <version>1.0</version>
                    </dependency>
                  </dependencies>
                </plugin>
                <plugin>
                  <groupId>org.codehaus.mojo</groupId>
                  <artifactId>exec-maven-plugin</artifactId>
                  <version>${maven.execmaven.plugin.version}</version>
                </plugin>
                <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${maven.antrun.plugin.version}</version>
                    <dependencies>
						<dependency>
							<groupId>com.percussion</groupId>
							<artifactId>rxutils</artifactId>
							<version>8.1.6-SNAPSHOT</version>
						</dependency>
						<dependency>
							<groupId>xerces</groupId>
							<artifactId>xercesImpl</artifactId>
							<version>${xerces.version}</version>
						</dependency>
                        <dependency>
							<groupId>xml-apis</groupId>
							<artifactId>xml-apis</artifactId>
							<version>1.4.01</version>
						</dependency>
						<dependency>
							<groupId>com.google.guava</groupId>
							<artifactId>guava</artifactId>
							<version>${guava.version}</version>
						</dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven.jar.plugin.version}</version>
                    <executions>
                        <execution>
                            <id>eclipse-jar</id>
                            <configuration>
                                <archive>
                                    <manifestFile>${manifest-location}/MANIFEST.MF</manifestFile>
                                </archive>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>${maven.dependency.plugin.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.apache.maven.resolver</groupId>
                            <artifactId>maven-resolver-api</artifactId>
                            <version>1.4.1</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>copy-eclipse-plugin-libs</id>
                            <phase>none</phase>
                            <goals>
                                <goal>copy-dependencies</goal>
                            </goals>
                            <configuration>
                                <outputDirectory>
                                    ${project.build.outputDirectory}/lib
                                </outputDirectory>
                            </configuration>
                        </execution>
                        <execution>
                            <id>generate-plugin-classpath</id>
                            <phase>none</phase>
                            <goals>
                                <goal>build-classpath</goal>
                            </goals>
                            <configuration>
                                <outputProperty>plugin-classpath</outputProperty>
                                <fileSeparator>/</fileSeparator>
                                <prefix>lib</prefix>
                                <pathSeparator>,</pathSeparator>
                                <excludeTransitive>false</excludeTransitive>
                                <overWriteReleases>false</overWriteReleases>
                                <overWriteSnapshots>false</overWriteSnapshots>
                                <overWriteIfNewer>true</overWriteIfNewer>
                                <excludeGroupIds>org.eclipse</excludeGroupIds>
                            </configuration>
                        </execution>

                    </executions>
                </plugin>
                <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                   <version>${maven.deploy.plugin.version}</version>
               </plugin>
                <!-- Reporting Plugins Can't define dependencies so
                     are listed here -->
             
                <!--  Enable at build time once rules are stable -->

                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <version>5.2.2</version>
                    <configuration>
                        <suppressionFiles>
                            <suppressionFile>owasp-suppressions.xml</suppressionFile>
                        </suppressionFiles>
                        <failBuildOnCVSS>8</failBuildOnCVSS>
                        <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                        <failOnError>true</failOnError>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven.source.jar.plugin.version}</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jxr-plugin</artifactId>
                <version>${maven.jxr.plugin.version}</version>
                <configuration>
                    <outputDirectory>${project.reporting.outputDirectory}/xref</outputDirectory>
                </configuration>
                <reportSets>
                    <reportSet>
                        <id>aggregate</id>
                        <reports>
                            <report>aggregate</report>
                            <report>test-aggregate</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-report-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven.checkstyle.plugin.version}</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>checkstyle</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>
  <dependencyManagement>
    <dependencies>
      <!-- Keep exactly one jakarta.annotation-api entry -->
      <dependency>
        <groupId>jakarta.annotation</groupId>
        <artifactId>jakarta.annotation-api</artifactId>
        <version>${jakarta.annotation.api.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
