#release configuration
#Fri Jun 26 16:40:21 EDT 2026
scm.commentPrefix=[maven-release-plugin] 
exec.pomFileName=pom.xml
pushChanges=false
releaseStrategyId=default
project.scm.com.percussion\:core.tag=HEAD
project.scm.com.percussion\:core.developerConnection=scm\:git\:https\://github.com/intersoftdatalabs-in/percussioncms
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
remoteTagging=true
exec.additionalArguments=-Dmaven.deploy.skip\=true
project.scm.com.percussion\:core.url=https\://github.com/intersoftdatalabs-in/percussioncms
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
projectVersionPolicyId=default
scm.url=scm\:git\:https\://github.com/intersoftdatalabs-in/percussioncms
scm.tagNameFormat=v@{project.version}
pinExternals=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
project.scm.com.percussion\:core.connection=scm\:git\:https\://github.com/intersoftdatalabs-in/percussioncms
exec.snapshotReleasePluginAllowed=false
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
completedPhase=check-poms
