"""Migration backlog generator.

Ported from ``scripts/release-audit/lib/backlog.sh``. Joins inventory.json
with verdicts.json, filters to ``needs-migration`` only, and emits a
prioritized Markdown backlog grouped by P0..P3 priority buckets.
"""
from __future__ import annotations

import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import common

LOGGER = logging.getLogger("release_audit.backlog")


def _priority_for(pr: dict[str, Any]) -> str:
    """Return ``P0``..``P3`` for ``pr`` based on securityFlag + modulePaths."""
    if pr.get("securityFlag"):
        return "P0"
    module_paths = pr.get("modulePaths", []) or []
    for mp in module_paths:
        if mp == "rest" or mp.startswith("projects/sitemanage") or mp.startswith(
            "deliverytiersuite/delivery-tier-suite"
        ):
            return "P1"
    for mp in module_paths:
        if mp.startswith("WebUI"):
            return "P2"
    return "P3"


PRIORITY_SECTIONS = {
    "P0": "P0 — Security",
    "P1": "P1 — REST contract / Publishing",
    "P2": "P2 — UI fix",
    "P3": "P3 — Cosmetic / Gadget",
}


def run_backlog_phase(repo_root: Path, output_dir: Path) -> None:
    """Generate ``migration-backlog.md`` from inventory + verdicts."""
    inventory_path = output_dir / "inventory.json"
    verdicts_path = output_dir / "verdicts.json"
    backlog_path = output_dir / "migration-backlog.md"
    config_path = output_dir / "_audit_config.json"
    if not inventory_path.is_file() or not verdicts_path.is_file():
        common.log_warn("inventory or verdicts missing; skipping backlog phase")
        return

    inventory = common.read_json(inventory_path)
    verdicts = common.read_json(verdicts_path)
    config = common.read_json(config_path) if config_path.is_file() else {}

    candidates: list[dict[str, Any]] = []
    verdicts_by_number = {v.get("prNumber"): v for v in verdicts}
    for pr in inventory:
        n = pr.get("number")
        v = verdicts_by_number.get(n, {})
        if v.get("verdict") != "needs-migration":
            continue
        candidates.append(
            {
                "number": n,
                "title": pr.get("title", ""),
                "mergedAt": pr.get("mergedAt", ""),
                "mergeCommitSha": pr.get("mergeCommitSha", ""),
                "author": pr.get("author", ""),
                "modulePaths": pr.get("modulePaths", []),
                "jdk8OnlyFlag": pr.get("jdk8OnlyFlag", False),
                "securityFlag": bool(v.get("securityFlag")) or bool(pr.get("securityFlag", False)),
                "verdict": v.get("verdict", "needs-migration"),
                "evidenceCommit": v.get("evidenceCommit", ""),
                "evidenceFilePath": v.get("evidenceFilePath", ""),
                "evidenceNote": v.get("evidenceNote", ""),
            }
        )

    from_tag = config.get("fromTag", "?")
    to_tag = config.get("toTag", "?")
    target_branch = config.get("targetBranch", "development")
    run_ts = config.get("runTimestamp") or datetime.now(timezone.utc).isoformat()

    lines: list[str] = [
        f"# Migration Backlog: {from_tag} → {to_tag}",
        "",
        f"**Tag range**: `{from_tag}..{to_tag}`  ",
        f"**Target branch**: `{target_branch}`  ",
        f"**Run timestamp**: {run_ts}  ",
        f"**Total backlog items**: {len(candidates)}  ",
        "",
        f"> Generated by `scripts/release-audit/__main__.py`. Each row is one v8.1.7 PR with verdict `needs-migration` against `{target_branch}`.",
        "",
    ]
    for prio in ("P0", "P1", "P2", "P3"):
        section = PRIORITY_SECTIONS[prio]
        prio_items = [c for c in candidates if _priority_for(c) == prio]
        lines.append(f"## {section}\n")
        if not prio_items:
            lines.append("_No items at this priority._\n")
            continue
        lines.append("| PR | Title | Module | Strategy | Test coverage in v8.1.7 | Blockers |")
        lines.append("|----|-------|--------|----------|------------------------|----------|")
        for c in prio_items:
            n = c.get("number")
            title = (c.get("title") or "")[:80]
            module = (c.get("modulePaths") or ["(none)"])[0]
            lines.append(
                f"| [#{n}](https://github.com/intersoftdatalabs-in/percussioncms/pull/{n}) | {title} | {module} | cherry-pick | _see v8.1.7 PR_ |  |"
            )
        lines.append("")

    lines.append("## Issue Clusters Appendix\n")
    lines.append("PRs grouped by GitHub issue reference extracted from titles.\n")
    lines.append("| Issue | PRs | Recommendation |")
    lines.append("|-------|-----|----------------|")
    clusters: dict[str, list[int]] = {}
    issue_re = re.compile(r"(?:#|GH-|issue )(?P<n>\d+)")
    for c in candidates:
        m = issue_re.search(c.get("title") or "")
        if not m:
            continue
        clusters.setdefault(m.group("n"), []).append(c.get("number"))
    for issue, prs in sorted(clusters.items(), key=lambda kv: int(kv[0])):
        prs_str = ", ".join(f"[#{n}]({n})" for n in prs)
        lines.append(f"| #{issue} | {prs_str} | _recommend latest merge_ |")
    lines.append("")

    common.write_atomic(backlog_path, "\n".join(lines))
    common.log_info(f"backlog written: {backlog_path}")
