<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.percussion</groupId>
        <artifactId>core</artifactId>
        <version>8.2.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <artifactId>webservices</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>${jakarta.xml.bind.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.jws</groupId>
            <artifactId>jakarta.jws-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.ws</groupId>
            <artifactId>jakarta.xml.ws-api</artifactId>
            <version>3.0.0</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-codegen-plugin</artifactId>
                <version>${cxf.version}</version>
                <executions>
                    <execution>
                        <id>wsdl2java</id>
                        <goals>
                            <goal>wsdl2java</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <sourceRoot>${project.build.directory}/generated-sources/cxf/wsdl2java</sourceRoot>
                            <wsdlOptions>
                                <wsdlOption>
                                    <wsdl>${basedir}/src/main/resources/com/percussion/webservices/design/rhythmyx.wsdl</wsdl>
                                    <packagenames>
                                        <packagename>urn:www.percussion.com/8.2.0=com.percussion.webservices.rhythmyx</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/rhythmyx=com.percussion.webservices.rhythmyx</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/assembly=com.percussion.webservices.assembly</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/assemblyServices=com.percussion.webservices.assembly.data</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/assemblyDesign=com.percussion.webservices.assemblydesign</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/content=com.percussion.webservices.content</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/contentDesign=com.percussion.webservices.contentdesign</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/system=com.percussion.webservices.system</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/systemDesign=com.percussion.webservices.systemdesign</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/common=com.percussion.webservices.common</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/faults=com.percussion.webservices.faults</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/security=com.percussion.webservices.securityservices</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/securityServices=com.percussion.webservices.security.data</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/securityDesign=com.percussion.webservices.securitydesign</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/ui=com.percussion.webservices.ui</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/uiServices=com.percussion.webservices.ui.data</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/uiDesign=com.percussion.webservices.uidesign</packagename>
                                    </packagenames>
                                    <extraargs>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-xjc -XautoNameResolution</extraarg>
                                        <extraarg>-b</extraarg>
                                        <extraarg>${basedir}/src/main/resources/com/percussion/webservices/design/jaxb-bindings-services.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${basedir}/src/main/resources/com/percussion/webservices/design/rhythmyxDesign.wsdl</wsdl>
                                    <packagenames>
                                        <packagename>urn:www.percussion.com/8.2.0=com.percussion.webservices.rhythmyx</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/rhythmyx=com.percussion.webservices.rhythmyx</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/rhythmyxDesign=com.percussion.webservices.rhythmyxdesign</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/assembly=com.percussion.webservices.assembly</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/assemblyDesign=com.percussion.webservices.assemblydesign</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/assemblyServices=com.percussion.webservices.assembly.data</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/content=com.percussion.webservices.content</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/contentDesign=com.percussion.webservices.contentdesign</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/system=com.percussion.webservices.system</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/systemDesign=com.percussion.webservices.systemdesign</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/common=com.percussion.webservices.common</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/faults=com.percussion.webservices.faults</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/security=com.percussion.webservices.securityservices</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/securityDesign=com.percussion.webservices.securitydesign</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/securityServices=com.percussion.webservices.security.data</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/ui=com.percussion.webservices.ui</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/uiDesign=com.percussion.webservices.uidesign</packagename>
                                        <packagename>urn:www.percussion.com/8.2.0/uiServices=com.percussion.webservices.ui.data</packagename>
                                    </packagenames>
                                    <extraargs>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-xjc -XautoNameResolution</extraarg>
                                        <extraarg>-b</extraarg>
                                        <extraarg>${basedir}/src/main/resources/com/percussion/webservices/design/jaxb-bindings-design.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                            </wsdlOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>add-cxf-source</id>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/cxf/wsdl2java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <sourcepath>${project.build.sourceDirectory}</sourcepath>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
