/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.percussion.webui.gadget.servlets;

import com.percussion.cms.IPSConstants;
import com.percussion.security.error.PSExceptionUtils;
import jakarta.servlet.Filter;
import jakarta.servlet.FilterChain;
import jakarta.servlet.FilterConfig;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URI;
import java.net.URISyntaxException;
import org.apache.commons.io.IOUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 * This class validates the urls passed in for Gadgets Meta calls to make sure urls passed in are
 * valid.
 */
public class GadgetRequestCacheFilter implements Filter {
  private static final Logger log = LogManager.getLogger(IPSConstants.DASHBOARD_LOG);
  private FilterConfig filterConfig = null;

  @Override
  public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
      throws IOException, ServletException {
    request = new GadgetRequestWrapper((HttpServletRequest) request);
    var gadgetUrl = request.getParameter("url");
    if (gadgetUrl != null && !gadgetUrl.isEmpty()) {
      try {
        if (!PSGadgetUtils.isValidGadgetPathInUrl(
            (HttpServletRequest) request, new URI(gadgetUrl))) {
          ((HttpServletResponse) response).sendError(404);
          return;
        }
      } catch (URISyntaxException e) {
        ((HttpServletResponse) response).setStatus(HttpServletResponse.SC_BAD_REQUEST);
        log.warn(
            "Invalid URL detected. URL: {} Error: {}. NOTE: These warnings may be generated by an"
                + " active application security scan.",
            gadgetUrl,
            PSExceptionUtils.getMessageForLog(e));
        return;
      }
    }
    var encoding = request.getCharacterEncoding();
    if (encoding == null) encoding = "UTF-8";
    JSONObject reqBody = null;
    try (var is = new InputStreamReader(request.getInputStream(), encoding)) {
      var body = IOUtils.toString(is);
      if (body != null && !body.isEmpty()) {
        reqBody = new JSONObject(new String(body.getBytes(), encoding));
        if (!validURLs((HttpServletRequest) request, (HttpServletResponse) response, reqBody)) {
          ((HttpServletResponse) response).sendError(404);
          return;
        }
      }
    }
    chain.doFilter(request, response);
  }

  private boolean validURLs(
      HttpServletRequest request, HttpServletResponse response, JSONObject reqBody) {
    try {
      var gadgets = (JSONArray) reqBody.get("gadgets");
      if (gadgets != null) {
        for (int i = 0; i < gadgets.length(); i++) {
          var gadget = gadgets.getJSONObject(i);
          var url = (String) gadget.get("url");
          if (!PSGadgetUtils.isValidGadgetPathInUrl(request, new URI(url))) {
            return false;
          }
        }
      }
      return true;
    } catch (URISyntaxException e) {
      response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
      log.error(PSExceptionUtils.getMessageForLog(e));
      return false;
    }
  }

  @Override
  public void init(FilterConfig filterConfiguration) throws ServletException {
    this.filterConfig = filterConfiguration;
  }

  @Override
  public void destroy() {
    this.filterConfig = null;
  }
}
