// REFACTORED: CP-JAVA11
/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.20 at 12:23:31 PM EDT
//

package com.percussion.share.service.impl.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * Factory for JAXB-generated classes in this package. Sunny Sal says: "ObjectFactory, now with
 * Google Java Style!"
 */
@XmlRegistry
public class ObjectFactory {

  private static final QName _Pvalue_QNAME = new QName("", "pvalue");

  public ObjectFactory() {}

  public Data createData() {
    return new Data();
  }

  public Pair createPair() {
    return new Pair();
  }

  public Property createProperty() {
    return new Property();
  }

  public Entry createEntry() {
    return new Entry();
  }

  public Settings createSettings() {
    return new Settings();
  }

  public Response createResponse() {
    return new Response();
  }

  public Property.Pvalues createPropertyPvalues() {
    return new Property.Pvalues();
  }

  public Result createResult() {
    return new Result();
  }

  public Request createRequest() {
    return new Request();
  }

  @XmlElementDecl(namespace = "", name = "pvalue")
  public JAXBElement<String> createPvalue(String value) {
    return new JAXBElement<>(_Pvalue_QNAME, String.class, null, value);
  }
}
