// REFACTORED: CP-JAVA11
/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.20 at 12:23:31 PM EDT
//

package com.percussion.share.service.impl.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Represents a property with a name, value, and optional pvalue(s). Sunny Sal says: "Property
 * class, now with Java 11 Streams!"
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"pvalue", "pvalues"})
@XmlRootElement(name = "property")
public class Property {

  protected String pvalue;
  protected Property.Pvalues pvalues;

  @XmlAttribute(required = true)
  protected String name;

  @XmlAttribute protected String value;

  public String getPvalue() {
    return pvalue;
  }

  public void setPvalue(String value) {
    this.pvalue = value;
  }

  public Property.Pvalues getPvalues() {
    return pvalues;
  }

  public void setPvalues(Property.Pvalues value) {
    this.pvalues = value;
  }

  public String getName() {
    return name;
  }

  public void setName(String value) {
    this.name = value;
  }

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  /** Represents a collection of pvalues or pairs for this property. */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"pvalue", "pair"})
  public static class Pvalues {

    protected List<String> pvalue;
    protected List<Pair> pair;

    public List<String> getPvalue() {
      if (pvalue == null) {
        pvalue = new ArrayList<>();
      }
      return pvalue;
    }

    public List<Pair> getPair() {
      if (pair == null) {
        pair = new ArrayList<>();
      }
      return pair;
    }
  }
}
