/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.percussion.server.compare;

import com.percussion.error.IPSErrorCode;
import com.percussion.error.PSException;

/**
 * A class to represent any errors generated by the compare package. The getMessage functions will
 * return internationalized messages.
 */
public class PSCompareException extends PSException {
  /**
   * Pass-through constructor to super class.
   *
   * @param language user's logged in language
   * @param msgCode error message code
   * @param singleArg argument
   * @see PSException#PSException(int,Object)
   */
  public PSCompareException(String language, int msgCode, Object singleArg) {
    super(language, msgCode, singleArg);
  }

  /**
   * Pass-through constructor to super class.
   *
   * @param language user's logged in language
   * @param msgCode error message code
   * @param arrayArgs arguments array
   * @see PSException#PSException(int,Object[])
   */
  public PSCompareException(String language, int msgCode, Object[] arrayArgs) {
    super(language, msgCode, arrayArgs);
  }

  /**
   * Pass-through constructor to super class.
   *
   * @param language user's logged in language
   * @param msgCode error message code
   * @see PSException#PSException(int)
   */
  public PSCompareException(String language, int msgCode) {
    super(language, msgCode);
  }

  /**
   * Typed construction with a locale and no message arguments.
   *
   * @param language user's logged in language
   * @param code catalogued error code, never {@code null}
   */
  public PSCompareException(String language, IPSErrorCode code) {
    super(language, code, (Object[]) null);
  }

  /**
   * Typed construction with a locale and a single message argument.
   *
   * @param language user's logged in language
   * @param code catalogued error code, never {@code null}
   * @param singleArg argument
   */
  public PSCompareException(String language, IPSErrorCode code, Object singleArg) {
    super(language, code, singleArg);
  }

  /**
   * Typed construction with a locale and message arguments.
   *
   * @param language user's logged in language
   * @param code catalogued error code, never {@code null}
   * @param arrayArgs arguments array
   */
  public PSCompareException(String language, IPSErrorCode code, Object[] arrayArgs) {
    super(language, code, arrayArgs);
  }
}
