/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.22 at 12:36:47 PM EDT 
//


package com.percussion.rx.config.impl.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.percussion.rx.config.impl.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Description_QNAME = new QName("", "description");
    private static final QName _Pvalue_QNAME = new QName("", "pvalue");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.percussion.rx.config.impl.jaxb
     */
    public ObjectFactory() {
    }

    public Entry createEntry() {
        return new Entry();
    }

    public Property createProperty() {
        return new Property();
    }

    public Pair createPair() {
        return new Pair();
    }

    public PropertySet createPropertySet() {
        return new PropertySet();
    }

    public Property.Pvalues createPropertyPvalues() {
        return new Property.Pvalues();
    }

    public SolutionConfigurations createSolutionConfigurations() {
        return new SolutionConfigurations();
    }

    public SolutionConfig createSolutionConfig() {
        return new SolutionConfig();
    }

    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<>(_Description_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "", name = "pvalue")
    public JAXBElement<String> createPvalue(String value) {
        return new JAXBElement<>(_Pvalue_QNAME, String.class, null, value);
    }
}
