/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.03.27 at 06:11:05 PM EDT
//

package com.percussion.rx.config.impl.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="pvalue1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pvalue2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="value1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {})
@XmlRootElement(name = "pair")
public class Pair {

  /** First element of the pair. */
  protected String pvalue1;

  /** Second element of the pair. */
  protected String pvalue2;

  /** First value attribute of the pair. */
  @XmlAttribute protected String value1;

  /** Second value attribute of the pair. */
  @XmlAttribute protected String value2;

  /** Default no-arg constructor required by JAXB. */
  public Pair() {}

  /**
   * Gets the value of the pvalue1 property.
   *
   * @return the pvalue1, may be null
   */
  public String getPvalue1() {
    return pvalue1;
  }

  /**
   * Sets the value of the pvalue1 property.
   *
   * @param value the pvalue1 to set, may be null
   */
  public void setPvalue1(String value) {
    this.pvalue1 = value;
  }

  /**
   * Gets the value of the pvalue2 property.
   *
   * @return the pvalue2, may be null
   */
  public String getPvalue2() {
    return pvalue2;
  }

  /**
   * Sets the value of the pvalue2 property.
   *
   * @param value the pvalue2 to set, may be null
   */
  public void setPvalue2(String value) {
    this.pvalue2 = value;
  }

  /**
   * Gets the value of the value1 property.
   *
   * @return the value1, may be null
   */
  public String getValue1() {
    return value1;
  }

  /**
   * Sets the value of the value1 property.
   *
   * @param value the value1 to set, may be null
   */
  public void setValue1(String value) {
    this.value1 = value;
  }

  /**
   * Gets the value of the value2 property.
   *
   * @return the value2, may be null
   */
  public String getValue2() {
    return value2;
  }

  /**
   * Sets the value of the value2 property.
   *
   * @param value the value2 to set, may be null
   */
  public void setValue2(String value) {
    this.value2 = value;
  }
}
