/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.03.27 at 06:11:05 PM EDT
//

package com.percussion.rx.config.impl.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}description" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{}pvalue" minOccurs="0"/>
 *           &lt;element name="pvalues" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice>
 *                     &lt;element ref="{}pvalue" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element ref="{}pair" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{}propertySet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="action" default="replace">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="merge"/>
 *             &lt;enumeration value="replace"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"description", "pvalue", "pvalues", "propertySet"})
@XmlRootElement(name = "property")
public class Property {

  /** Optional human-readable description of the property. */
  protected String description;

  /** Optional single string value of the property. */
  protected String pvalue;

  /** Optional collection of values for properties that take multiple values. */
  protected Property.Pvalues pvalues;

  /** Optional nested property sets contained within this property. */
  protected List<PropertySet> propertySet;

  /** Required name of the property. */
  @XmlAttribute(required = true)
  protected String name;

  /** Optional scalar value of the property. */
  @XmlAttribute protected String value;

  /**
   * Action to take when applying the property. Allowed values are defined by the schema and default
   * to {@code replace} when not set.
   */
  @XmlAttribute
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String action;

  /** Default no-arg constructor required by JAXB. */
  public Property() {}

  /**
   * Gets the value of the description property.
   *
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the pvalue property.
   *
   * @return possible object is {@link String }
   */
  public String getPvalue() {
    return pvalue;
  }

  /**
   * Sets the value of the pvalue property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPvalue(String value) {
    this.pvalue = value;
  }

  /**
   * Gets the value of the pvalues property.
   *
   * @return possible object is {@link Property.Pvalues }
   */
  public Property.Pvalues getPvalues() {
    return pvalues;
  }

  /**
   * Sets the value of the pvalues property.
   *
   * @param value allowed object is {@link Property.Pvalues }
   */
  public void setPvalues(Property.Pvalues value) {
    this.pvalues = value;
  }

  /**
   * Gets the value of the propertySet property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the propertySet property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPropertySet().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link PropertySet }
   *
   * @return the list of PropertySet objects
   */
  public List<PropertySet> getPropertySet() {
    if (propertySet == null) {
      propertySet = new ArrayList<>();
    }
    return this.propertySet;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the value property.
   *
   * @return possible object is {@link String }
   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   *
   * @param value allowed object is {@link String }
   */
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * Gets the value of the action property.
   *
   * @return possible object is {@link String }
   */
  public String getAction() {
    return action == null ? "replace" : action;
  }

  /**
   * Sets the value of the action property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAction(String value) {
    this.action = value;
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;choice>
   *         &lt;element ref="{}pvalue" maxOccurs="unbounded" minOccurs="0"/>
   *         &lt;element ref="{}pair" maxOccurs="unbounded" minOccurs="0"/>
   *       &lt;/choice>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"pvalue", "pair"})
  public static class Pvalues {

    /** The list of pvalue string elements. */
    protected List<String> pvalue;

    /** The list of pair elements. */
    protected List<Pair> pair;

    /** Default no-arg constructor required by JAXB. */
    public Pvalues() {}

    /**
     * Gets the value of the pvalue property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the pvalue property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getPvalue().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link String }
     *
     * @return the list of pvalue strings
     */
    public List<String> getPvalue() {
      if (pvalue == null) {
        pvalue = new ArrayList<>();
      }
      return this.pvalue;
    }

    /**
     * Gets the value of the pair property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the pair property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getPair().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link Pair }
     *
     * @return the list of Pair objects
     */
    public List<Pair> getPair() {
      if (pair == null) {
        pair = new ArrayList<>();
      }
      return this.pair;
    }
  }
}
