/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.03.27 at 06:11:05 PM EDT
//

package com.percussion.rx.config.impl.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}description" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}propertySet" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}property" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="action" default="update">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="remove"/>
 *             &lt;enumeration value="update"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"description", "propertySetOrProperty"})
@XmlRootElement(name = "propertySet")
public class PropertySet {

  /** Optional human-readable description of the property set. */
  protected String description;

  /**
   * The list of nested Property and PropertySet elements contained within this property set. May
   * contain instances of {@link Property} or {@link PropertySet}.
   */
  @XmlElements({
    @XmlElement(name = "property", type = Property.class),
    @XmlElement(name = "propertySet", type = PropertySet.class)
  })
  protected List<Object> propertySetOrProperty;

  /**
   * Action to take when applying the property set. Allowed values are defined by the schema and
   * default to {@code update} when not set.
   */
  @XmlAttribute
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String action;

  /** Optional name of the property set. */
  @XmlAttribute protected String name;

  /** Default no-arg constructor required by JAXB. */
  public PropertySet() {}

  /**
   * Gets the value of the description property.
   *
   * @return the description, may be null
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value the description to set, may be null
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the propertySetOrProperty property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object.
   *
   * @return the list of Property or PropertySet objects
   */
  public List<Object> getPropertySetOrProperty() {
    if (propertySetOrProperty == null) {
      propertySetOrProperty = new ArrayList<>();
    }
    return this.propertySetOrProperty;
  }

  /**
   * Gets the value of the action property.
   *
   * @return the action, defaults to "update" if null
   */
  public String getAction() {
    return action == null ? "update" : action;
  }

  /**
   * Sets the value of the action property.
   *
   * @param value the action to set, may be null
   */
  public void setAction(String value) {
    this.action = value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return the name, may be null
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value the name to set, may be null
   */
  public void setName(String value) {
    this.name = value;
  }
}
