/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.05.22 at 12:36:47 PM EDT
//

package com.percussion.rx.config.impl.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SolutionConfig" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="publisherPrefix" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="publisherName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"solutionConfig"})
@XmlRootElement(name = "SolutionConfigurations")
public class SolutionConfigurations {

  /** Default constructor for JAXB. */
  public SolutionConfigurations() {}

  /** The list of {@link SolutionConfig} objects, required. */
  @XmlElement(name = "SolutionConfig", required = true)
  protected List<SolutionConfig> solutionConfig;

  /** The required publisher prefix. */
  @XmlAttribute(required = true)
  protected String publisherPrefix;

  /** The required publisher name. */
  @XmlAttribute(required = true)
  protected String publisherName;

  /**
   * Gets the value of the solutionConfig property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object.
   *
   * @return the list of SolutionConfig objects
   */
  public List<SolutionConfig> getSolutionConfig() {
    if (solutionConfig == null) {
      solutionConfig = new ArrayList<>();
    }
    return this.solutionConfig;
  }

  /**
   * Gets the value of the publisherPrefix property.
   *
   * @return the publisherPrefix, may be null
   */
  public String getPublisherPrefix() {
    return publisherPrefix;
  }

  /**
   * Sets the value of the publisherPrefix property.
   *
   * @param value the publisherPrefix to set, may be null
   */
  public void setPublisherPrefix(String value) {
    this.publisherPrefix = value;
  }

  /**
   * Gets the value of the publisherName property.
   *
   * @return the publisherName, may be null
   */
  public String getPublisherName() {
    return publisherName;
  }

  /**
   * Sets the value of the publisherName property.
   *
   * @param value the publisherName to set, may be null
   */
  public void setPublisherName(String value) {
    this.publisherName = value;
  }
}
