<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ Hibernate, Relational Persistence for Idiomatic Java
  ~
  ~ License: GNU Lesser General Public License (LGPL), version 2.1 or later.
  ~ See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.hibernate.org/xsd/orm/hibernate-configuration"
           targetNamespace="http://www.hibernate.org/xsd/orm/hibernate-configuration"
           elementFormDefault="qualified">

    <xs:element name="hibernate-configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="session-factory" minOccurs="0">
                    <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="mapping" type="mappingType" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="cache" type="cacheType" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="event" type="eventType" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="listener" type="listenerType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:choice>
                        <xs:attribute name="name" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="propertyType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="mappingType">
        <xs:attribute name="resource" type="xs:string"/>
        <xs:attribute name="file" type="xs:string"/>
        <xs:attribute name="jar" type="xs:string"/>
        <xs:attribute name="package" type="xs:string"/>
        <xs:attribute name="class" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="cacheType">
        <xs:attribute name="region" type="xs:string"/>
        <xs:attribute name="class" type="xs:string"/>
        <xs:attribute name="collection" type="xs:string"/>
        <xs:attribute name="usage" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="read-only"/>
                    <xs:enumeration value="read-write"/>
                    <xs:enumeration value="nonstrict-read-write"/>
                    <xs:enumeration value="transactional"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="include">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="all"/>
                    <xs:enumeration value="non-lazy"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="eventType">
        <xs:sequence>
            <xs:element name="listener" type="listenerType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="listenerType">
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="class" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>
