/*
 * Copyright (c) 2026 Intersoft Data Labs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.intsof.percussioncms.auditlog.codes;

import com.intsof.percussioncms.auditlog.AuditEventType;
import com.intsof.percussioncms.auditlog.AuditModule;
import com.intsof.percussioncms.auditlog.AuditOutcome;
import com.intsof.percussioncms.auditlog.LegacyErrorCodeRegistry;
import com.intsof.percussioncms.auditlog.SystemErrorCode;

/**
 * Server error catalog bridging legacy {@code com.percussion.server.IPSServerErrors} ints
 * (ranges 1001–1709: general, application handlers, loadable handlers, server internals,
 * request preparation, console, remote console, content-editor processing).
 *
 * <p>{@link #numericCode()} preserves historical ints. Every constant sets {@link #isAuditable()}
 * explicitly: authentication / authorization / community / credentials failures dual-write;
 * operational, parse, console, and CE structure noise does not.
 *
 * <p>Module code is {@link AuditModule#SYS}.
 */
public enum ServerErrorCodes implements SystemErrorCode {
  NATIVE_ERROR(
      1001,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Native error",
      "Native error detail={}"),
  RAW_DUMP(
      1002,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Raw dump",
      "Raw dump detail={}"),
  DATA_CONV_ERROR(
      1003,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Data conv error",
      "Data conv error detail={}"),
  REQ_DOC_MISSING(
      1004,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req doc missing",
      "Req doc missing detail={}"),
  REQ_DOC_INVALID_TYPE(
      1005,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req doc invalid type",
      "Req doc invalid type detail={}"),
  ARGUMENT_OUT_OF_RANGE(
      1006,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Argument out of range",
      "Argument out of range detail={}"),
  ARGUMENT_ERROR(
      1007,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Argument error",
      "Argument error detail={}"),
  UNKNOWN_PROCESSING_ERROR(
      1008,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Unknown processing error",
      "Unknown processing error detail={}"),
  RESPONSE_SEND_ERROR(
      1009,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Response send error",
      "Response send error detail={}"),
  REDIRECT_URL_TOO_LONG(
      1010,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Redirect url too long",
      "Redirect url too long detail={}"),
  WRAPPED_LOG_ERROR(
      1011,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Wrapped log error",
      "Wrapped log error detail={}"),
  UNKNOWN_HOST(
      1012,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Unknown host",
      "Unknown host detail={}"),
  SERVER_LOCK_NOT_ACQUIRED(
      1013,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server lock not acquired",
      "Server lock not acquired detail={}"),
  SQL_PROBLEM(
      1014,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Sql problem",
      "Sql problem detail={}"),
  RUNNING_SERVER_LOCK_NOT_ACQUIRED(
      1015,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Running server lock not acquired",
      "Running server lock not acquired detail={}"),
  AUTHORIZATION_ERROR(
      1101,
      true,
      AuditEventType.ACCESS_DENIED,
      AuditOutcome.FAILURE,
      "Authorization error",
      "Server authorization error session={} resource={}"),
  POOR_RESPONSE_TIME(
      1102,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Poor response time",
      "Poor response time detail={}"),
  REQUEST_QUEUE_FULL(
      1103,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Request queue full",
      "Request queue full detail={}"),
  VALIDATION_ERROR(
      1104,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Validation error",
      "Validation error detail={}"),
  TOO_MANY_LOGIN_ATTEMPTS(
      1105,
      true,
      AuditEventType.AUTH_FAILURE,
      AuditOutcome.FAILURE,
      "Too many login attempts",
      "Too many login attempts session={} detail={}"),
  EMPTY_DATASET(
      1106,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Empty dataset",
      "Empty dataset detail={}"),
  NO_DATASET_DEFINITIONS(
      1107,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "No dataset definitions",
      "No dataset definitions detail={}"),
  REQUEST_PREPROC_ERROR(
      1108,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Request preproc error",
      "Request preproc error detail={}"),
  NULL_APPLICATION_ERROR(
      1109,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Null application error",
      "Null application error detail={}"),
  APP_DATASET_NOT_FOUND(
      1110,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App dataset not found",
      "App dataset not found detail={}"),
  APP_DATASET_HANDLER_NOT_FOUND(
      1111,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App dataset handler not found",
      "App dataset handler not found detail={}"),
  APP_DATASET_INVALID(
      1112,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App dataset invalid",
      "App dataset invalid detail={}"),
  APP_NO_QUERY_PIPES_IN_DATASET(
      1113,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App no query pipes in dataset",
      "App no query pipes in dataset detail={}"),
  APP_NO_UPDATE_PIPES_IN_DATASET(
      1114,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App no update pipes in dataset",
      "App no update pipes in dataset detail={}"),
  APP_DATASET_DEF_NOT_FOUND(
      1115,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App dataset def not found",
      "App dataset def not found detail={}"),
  APP_LOGIN_PAGE_EXCEPTION(
      1116,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App login page exception",
      "App login page exception detail={}"),
  DEFINE_ROLE_ENTRY_EXCEPTION(
      1117,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Define role entry exception",
      "Define role entry exception detail={}"),
  APP_START_EXCEPTION(
      1118,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App start exception",
      "App start exception detail={}"),
  VALIDATION_RULES_NOT_MET(
      1119,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Validation rules not met",
      "Validation rules not met detail={}"),
  NO_AUTHORIZATION(
      1120,
      true,
      AuditEventType.ACCESS_DENIED,
      AuditOutcome.FAILURE,
      "No authorization for request",
      "No authorization session={} resource={}"),
  CE_SYSTEM_DEF_LOAD(
      1121,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce system def load",
      "Ce system def load detail={}"),
  CE_SHARED_DEF_LOAD(
      1122,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce shared def load",
      "Ce shared def load detail={}"),
  APP_FILE_DOES_NOT_EXIST(
      1123,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App file does not exist",
      "App file does not exist detail={}"),
  APP_ONLY_XML_FILES_SUPPORTED(
      1124,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App only xml files supported",
      "App only xml files supported detail={}"),
  APP_ADDED_SYSTEM_MANDATORY_FIELDS(
      1125,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "App added system mandatory fields",
      "App added system mandatory fields detail={}"),
  ACTION_SET_MISSING_REQUIRED_PARAMS(
      1176,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Action set missing required params",
      "Action set missing required params detail={}"),
  ACTION_SET_COULD_NOT_DETERMINE_CE(
      1177,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Action set could not determine ce",
      "Action set could not determine ce detail={}"),
  ACTION_SET_ACTION_NOT_FOUND(
      1178,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Action set action not found",
      "Action set action not found detail={}"),
  ACTION_SET_INVALID_STYLESHEET(
      1179,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Action set invalid stylesheet",
      "Action set invalid stylesheet detail={}"),
  ACTION_SET_INVALID_EXTENSION(
      1180,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Action set invalid extension",
      "Action set invalid extension detail={}"),
  ACTION_SET_DUPLICATE_NAME(
      1181,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Action set duplicate name",
      "Action set duplicate name detail={}"),
  ACTION_SET_MISSING_CATALOGER(
      1182,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Action set missing cataloger",
      "Action set missing cataloger detail={}"),
  ACTION_DUPLICATE_NAME(
      1183,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Action duplicate name",
      "Action duplicate name detail={}"),
  LOADABLE_HANDLER_CONFIGURATION_FILE_IS_NULL(
      1184,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Loadable handler configuration file is null",
      "Loadable handler configuration file is null detail={}"),
  LOADABLE_HANDLER_CONFIGURATION_FILE_IS_INVALID(
      1185,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Loadable handler configuration file is invalid",
      "Loadable handler configuration file is invalid detail={}"),
  LOADABLE_HANDLER_UNEXPECTED_EXCEPTION(
      1186,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Loadable handler unexpected exception",
      "Loadable handler unexpected exception detail={}"),
  SERVER_SHUTDOWN_MSG(
      1201,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server shutdown msg",
      "Server shutdown msg detail={}"),
  FATAL_SERVER_ERROR_MSG(
      1202,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Fatal server error msg",
      "Fatal server error msg detail={}"),
  EXCEPTION_NOT_CAUGHT(
      1203,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Exception not caught",
      "Exception not caught detail={}"),
  LOAD_CONFIG_FAILURE(
      1204,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Load config failure",
      "Load config failure detail={}"),
  LOG_INIT_BAD_CONFIG(
      1205,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Log init bad config",
      "Log init bad config detail={}"),
  LOG_INIT_FILE_ERROR(
      1206,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Log init file error",
      "Log init file error detail={}"),
  LOG_INIT_SQL_ERROR(
      1207,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Log init sql error",
      "Log init sql error detail={}"),
  LOG_INIT_DRIVER_ERROR(
      1208,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Log init driver error",
      "Log init driver error detail={}"),
  SERVER_INTERRUPT_CAUGHT(
      1209,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server interrupt caught",
      "Server interrupt caught detail={}"),
  OBJECT_STORE_INIT_FAILED(
      1210,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Object store init failed",
      "Object store init failed detail={}"),
  LOG_INIT_XML_FILE_ERROR(
      1211,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Log init xml file error",
      "Log init xml file error detail={}"),
  INTERNAL_SERVER_ERROR_MSG(
      1212,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Internal server error msg",
      "Internal server error msg detail={}"),
  USER_THR_POOL_WAIT_EXCEPTION(
      1213,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "User thr pool wait exception",
      "User thr pool wait exception detail={}"),
  STREAM_NOT_OPENED(
      1214,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Stream not opened",
      "Stream not opened detail={}"),
  STREAM_ALREADY_OPENED(
      1215,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Stream already opened",
      "Stream already opened detail={}"),
  STREAM_ALREADY_CLOSED(
      1216,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Stream already closed",
      "Stream already closed detail={}"),
  EVENT_QUEUEMGR_NULL(
      1217,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Event queuemgr null",
      "Event queuemgr null detail={}"),
  USER_THR_UNCAUGHT_EXCEPTION(
      1218,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "User thr uncaught exception",
      "User thr uncaught exception detail={}"),
  LOG_SIZE_TOO_BIG(
      1219,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Log size too big",
      "Log size too big detail={}"),
  SERVER_UNAVAILABLE_ERROR_MSG(
      1220,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server unavailable error msg",
      "Server unavailable error msg detail={}"),
  SERVER_INITIALIZING_ERROR_MSG(
      1221,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server initializing error msg",
      "Server initializing error msg detail={}"),
  DAEMON_THR_UNCAUGHT_EXCEPTION(
      1222,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Daemon thr uncaught exception",
      "Daemon thr uncaught exception detail={}"),
  SERVER_BRAND_VALIDATOR_FAILURE(
      1223,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server brand validator failure",
      "Server brand validator failure detail={}"),
  CACHE_UNEXPECTED_EXCEPTION(
      1224,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cache unexpected exception",
      "Cache unexpected exception detail={}"),
  CACHE_NOT_STARTED(
      1225,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cache not started",
      "Cache not started detail={}"),
  CACHE_NO_INTERNAL_REQUEST_HANDLER(
      1226,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cache no internal request handler",
      "Cache no internal request handler detail={}"),
  CACHE_INTERNAL_REQUEST_FAILURE(
      1227,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cache internal request failure",
      "Cache internal request failure detail={}"),
  CACHE_DEPENDENCY_SKIPPED(
      1228,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cache dependency skipped",
      "Cache dependency skipped detail={}"),
  CACHE_CURRENTREVISION_UPDATE_FAILURE(
      1229,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cache currentrevision update failure",
      "Cache currentrevision update failure detail={}"),
  CACHE_STORE_TO_DISK_FAILURE(
      1230,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cache store to disk failure",
      "Cache store to disk failure detail={}"),
  CACHE_START_FAILED(
      1231,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cache start failed",
      "Cache start failed detail={}"),
  RELATIONSHIP_INTERNAL_REQUEST_FAILURE(
      1232,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Relationship internal request failure",
      "Relationship internal request failure detail={}"),
  MISSING_INTERNAL_REQUEST_RESOURCE(
      1233,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Missing internal request resource",
      "Missing internal request resource detail={}"),
  INVALID_CONFIGURATION(
      1234,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid configuration",
      "Invalid configuration detail={}"),
  INVALID_CONFIG_OBJECT(
      1235,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid config object",
      "Invalid config object detail={}"),
  UNKNOWN_CONFIGURATION(
      1236,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Unknown configuration",
      "Unknown configuration detail={}"),
  UNKNOWN_RELATIONSHIP_CONFIGURATION(
      1237,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Unknown relationship configuration",
      "Unknown relationship configuration detail={}"),
  UNKNOWN_CLONEHANDLER_CONFIGURATION(
      1238,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Unknown clonehandler configuration",
      "Unknown clonehandler configuration detail={}"),
  UNKNOWN_EFFECT_PROCESSING_ERROR(
      1239,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Unknown effect processing error",
      "Unknown effect processing error detail={}"),
  EFFECT_PROCESSING_FAILED(
      1240,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Effect processing failed",
      "Effect processing failed detail={}"),
  RELATIONSHIP_ALREADY_EXISTS(
      1241,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Relationship already exists",
      "Relationship already exists detail={}"),
  CONFIG_NOT_ALLOWED_EDIT(
      1242,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Config not allowed edit",
      "Config not allowed edit detail={}"),
  CONFIG_LOCKED(
      1243,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Config locked",
      "Config locked detail={}"),
  CONFIG_LOCKED_SAME(
      1244,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Config locked same",
      "Config locked same detail={}"),
  TRANSITION_REJECTED(
      1245,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Transition rejected",
      "Transition rejected detail={}"),
  CACHE_HANDLER_DUPE_TYPE(
      1246,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cache handler dupe type",
      "Cache handler dupe type detail={}"),
  COMMUNITIES_AUTHENTICATION_FAILED_INVALID_COMMUNITY(
      1247,
      true,
      AuditEventType.AUTH_FAILURE,
      AuditOutcome.FAILURE,
      "Community authentication failed",
      "Communities authentication failed invalid community user={} community={}"),
  COMMUNITIES_AUTHENTICATION_FAILED_ERROR(
      1248,
      true,
      AuditEventType.AUTH_FAILURE,
      AuditOutcome.FAILURE,
      "Community authentication failed",
      "Communities authentication failed error user={} detail={}"),
  ERROR_LOAD_CONFIGS(
      1249,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Error load configs",
      "Error load configs detail={}"),
  ERROR_UPDATE_CONFIG(
      1250,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Error update config",
      "Error update config detail={}"),
  INVALID_REQUEST_LINE(
      1301,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid request line",
      "Invalid request line detail={}"),
  INVALID_REQUEST_METHOD(
      1302,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid request method",
      "Invalid request method detail={}"),
  INVALID_CONTENT_LENGTH(
      1303,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid content length",
      "Invalid content length detail={}"),
  INVALID_CONTENT_TYPE(
      1304,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid content type",
      "Invalid content type detail={}"),
  PARSER_UNSUPPORTED_CONTENT_TYPE(
      1305,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Parser unsupported content type",
      "Parser unsupported content type detail={}"),
  XML_PARSER_SAX_ERROR(
      1306,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Xml parser sax error",
      "Xml parser sax error detail={}"),
  JSON_PARSER_ERROR(
      1316,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Json parser error",
      "Json parser error detail={}"),
  FORM_PARSER_BAD_HEX_CHAR(
      1307,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Form parser bad hex char",
      "Form parser bad hex char detail={}"),
  REQUEST_HANDLER_NOT_FOUND(
      1308,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Request handler not found",
      "Request handler not found detail={}"),
  REQUEST_PAGE_TYPE_ERROR(
      1309,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Request page type error",
      "Request page type error detail={}"),
  INVALID_MULTIPART_CONTENT_TYPE(
      1310,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid multipart content type",
      "Invalid multipart content type detail={}"),
  INVALID_MULTIPART_CONTENT_DISP(
      1311,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid multipart content disp",
      "Invalid multipart content disp detail={}"),
  REQUEST_WAIT_TOO_LONG(
      1312,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Request wait too long",
      "Request wait too long detail={}"),
  REQUEST_TIMEOUT_INVALID_USING_DEFAULT(
      1313,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Request timeout invalid using default",
      "Request timeout invalid using default detail={}"),
  REQUEST_QUEUE_DEPTH_INVALID_USING_DEFAULT(
      1314,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Request queue depth invalid using default",
      "Request queue depth invalid using default detail={}"),
  CONTENT_LENGTH_DOES_NOT_MATCH_DATA_READ(
      1315,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Content length does not match data read",
      "Content length does not match data read detail={}"),
  CAPACITY_REACHED_MSG(
      1330,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Capacity reached msg",
      "Capacity reached msg detail={}"),
  LISTENER_DEAD(
      1331,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Listener dead",
      "Listener dead detail={}"),
  NULL_CONNECTION_LISTENER(
      1332,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Null connection listener",
      "Null connection listener detail={}"),
  REQUEST_HANDLER_CONFIG_NOT_FOUND(
      1333,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Request handler config not found",
      "Request handler config not found detail={}"),
  REQUEST_HANDLER_CONFIG_ERROR(
      1334,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Request handler config error",
      "Request handler config error detail={}"),
  LOADABLE_REQUEST_HANDLER_CREATE_ERROR(
      1335,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Loadable request handler create error",
      "Loadable request handler create error detail={}"),
  SERVER_INIT_START(
      1401,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server init start",
      "Server init start detail={}"),
  LOADING_CONFIG(
      1402,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Loading config",
      "Loading config detail={}"),
  SERVER_INIT_END(
      1403,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server init end",
      "Server init end detail={}"),
  SERVER_TERM_START(
      1404,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server term start",
      "Server term start detail={}"),
  SERVER_TERM_END(
      1405,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server term end",
      "Server term end detail={}"),
  SIG_HANDLER_NOT_STARTED(
      1406,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Sig handler not started",
      "Sig handler not started detail={}"),
  DB_POOL_INIT(
      1411,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Db pool init",
      "Db pool init detail={}"),
  DB_POOL_TERM(
      1412,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Db pool term",
      "Db pool term detail={}"),
  DB_POOL_TERM_EXCEPTION(
      1413,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Db pool term exception",
      "Db pool term exception detail={}"),
  USER_THREAD_POOL_INIT(
      1414,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "User thread pool init",
      "User thread pool init detail={}"),
  USER_THREAD_POOL_TERM(
      1415,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "User thread pool term",
      "User thread pool term detail={}"),
  USER_THREAD_POOL_TERM_EXCEPTION(
      1416,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "User thread pool term exception",
      "User thread pool term exception detail={}"),
  OBJECT_STORE_INIT(
      1417,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Object store init",
      "Object store init detail={}"),
  OBJECT_STORE_TERM(
      1418,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Object store term",
      "Object store term detail={}"),
  OBJECT_STORE_TERM_EXCEPTION(
      1419,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Object store term exception",
      "Object store term exception detail={}"),
  REQ_HANDLER_INIT(
      1420,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req handler init",
      "Req handler init detail={}"),
  REQ_HANDLER_TERM(
      1421,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req handler term",
      "Req handler term detail={}"),
  REQ_HANDLER_TERM_EXCEPTION(
      1422,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req handler term exception",
      "Req handler term exception detail={}"),
  LOG_MGR_INIT(
      1423,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Log mgr init",
      "Log mgr init detail={}"),
  LOG_MGR_TERM(
      1424,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Log mgr term",
      "Log mgr term detail={}"),
  LOG_MGR_TERM_EXCEPTION(
      1425,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Log mgr term exception",
      "Log mgr term exception detail={}"),
  ERROR_MGR_INIT(
      1426,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Error mgr init",
      "Error mgr init detail={}"),
  ERROR_MGR_TERM(
      1427,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Error mgr term",
      "Error mgr term detail={}"),
  ERROR_MGR_TERM_EXCEPTION(
      1428,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Error mgr term exception",
      "Error mgr term exception detail={}"),
  REQ_QUEUE_INIT(
      1429,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req queue init",
      "Req queue init detail={}"),
  REQ_QUEUE_TERM(
      1430,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req queue term",
      "Req queue term detail={}"),
  REQ_QUEUE_TERM_EXCEPTION(
      1431,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req queue term exception",
      "Req queue term exception detail={}"),
  REQ_LISTENER_INIT(
      1432,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req listener init",
      "Req listener init detail={}"),
  REQ_LISTENER_TERM(
      1433,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req listener term",
      "Req listener term detail={}"),
  REQ_LISTENER_TERM_EXCEPTION(
      1434,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req listener term exception",
      "Req listener term exception detail={}"),
  APPLICATION_INIT(
      1435,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Application init",
      "Application init detail={}"),
  APPLICATION_INIT_EXCEPTION(
      1436,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Application init exception",
      "Application init exception detail={}"),
  APPLICATION_TERM(
      1437,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Application term",
      "Application term detail={}"),
  SEC_POOL_INIT(
      1438,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Sec pool init",
      "Sec pool init detail={}"),
  SEC_POOL_TERM(
      1439,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Sec pool term",
      "Sec pool term detail={}"),
  SEC_POOL_TERM_EXCEPTION(
      1440,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Sec pool term exception",
      "Sec pool term exception detail={}"),
  REQ_QUEUE_INIT_EXCEPTION(
      1441,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Req queue init exception",
      "Req queue init exception detail={}"),
  APPLICATION_INIT_COMPLETED(
      1442,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Application init completed",
      "Application init completed detail={}"),
  EXTENSION_MGR_INIT_EXCEPTION(
      1443,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Extension mgr init exception",
      "Extension mgr init exception detail={}"),
  EXTENSION_MGR_TERM_EXCEPTION(
      1444,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Extension mgr term exception",
      "Extension mgr term exception detail={}"),
  SERVER_INIT_CASE_INSENSITIVE_URLS(
      1445,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Server init case insensitive urls",
      "Server init case insensitive urls detail={}"),
  UNEXPECTED_EXCEPTION_CONSOLE(
      1446,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Unexpected exception console",
      "Unexpected exception console detail={}"),
  UNEXPECTED_EXCEPTION_LOG(
      1447,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Unexpected exception log",
      "Unexpected exception log detail={}"),
  PROCESSOR_VALIDATION_ERROR(
      1448,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Processor validation error",
      "Processor validation error detail={}"),
  MACROS_INIT(
      1449,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Macros init",
      "Macros init detail={}"),
  INVALID_USER_MACROS(
      1450,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid user macros",
      "Invalid user macros detail={}"),
  LOCK_MANAGER_INITIALIZED(
      1451,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Lock manager initialized",
      "Lock manager initialized detail={}"),
  INVALID_CTRL_FILE_EXT(
      1452,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid ctrl file ext",
      "Invalid ctrl file ext detail={}"),
  INVALID_CTRL_FILE_MISSING_CTRL(
      1453,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid ctrl file missing ctrl",
      "Invalid ctrl file missing ctrl detail={}"),
  INVALID_CTRL_FILE_MULT_CTRLS(
      1454,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid ctrl file mult ctrls",
      "Invalid ctrl file mult ctrls detail={}"),
  INVALID_CTRL_FILE_NAME(
      1455,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid ctrl file name",
      "Invalid ctrl file name detail={}"),
  RCONSOLE_CONN_OBJ_NULL(
      1501,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole conn obj null",
      "Rconsole conn obj null detail={}"),
  RCONSOLE_CMD_EMPTY(
      1502,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole cmd empty",
      "Rconsole cmd empty detail={}"),
  RCONSOLE_INVALID_CMD(
      1503,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole invalid cmd",
      "Rconsole invalid cmd detail={}"),
  RCONSOLE_INVALID_SUBCMD(
      1504,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole invalid subcmd",
      "Rconsole invalid subcmd detail={}"),
  RCONSOLE_SUBCMD_REQD(
      1505,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole subcmd reqd",
      "Rconsole subcmd reqd detail={}"),
  RCONSOLE_UNEXPECTED_ARGS(
      1506,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole unexpected args",
      "Rconsole unexpected args detail={}"),
  RCONSOLE_APP_NAME_REQD(
      1507,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole app name reqd",
      "Rconsole app name reqd detail={}"),
  RCONSOLE_GET_HANDLER_EXCEPTION(
      1508,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole get handler exception",
      "Rconsole get handler exception detail={}"),
  RCONSOLE_APP_NOT_ACTIVE(
      1509,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole app not active",
      "Rconsole app not active detail={}"),
  RCONSOLE_APP_STATS_NOT_ENABLED(
      1510,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole app stats not enabled",
      "Rconsole app stats not enabled detail={}"),
  RCONSOLE_SERVER_SHUTDOWN_SCHEDULED(
      1511,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole server shutdown scheduled",
      "Rconsole server shutdown scheduled detail={}"),
  RCONSOLE_SERVER_STATS_NOT_ENABLED(
      1512,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole server stats not enabled",
      "Rconsole server stats not enabled detail={}"),
  RCONSOLE_APP_SHUTDOWN(
      1513,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole app shutdown",
      "Rconsole app shutdown detail={}"),
  RCONSOLE_APP_STARTED(
      1514,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole app started",
      "Rconsole app started detail={}"),
  RCONSOLE_APP_RESTARTED(
      1515,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole app restarted",
      "Rconsole app restarted detail={}"),
  RCONSOLE_EXEC_EXCEPTION(
      1516,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole exec exception",
      "Rconsole exec exception detail={}"),
  RCONSOLE_INVALID_ARGS(
      1517,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole invalid args",
      "Rconsole invalid args detail={}"),
  RCONSOLE_COMMAND_EXCEPTION(
      1518,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole command exception",
      "Rconsole command exception detail={}"),
  RCONSOLE_COMMAND_ERROR_MSG(
      1519,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole command error msg",
      "Rconsole command error msg detail={}"),
  HOOK_REQUEST_ERROR_MSG(
      1520,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Hook request error msg",
      "Hook request error msg detail={}"),
  HOOK_REQUEST_DOC_REQUIRED(
      1521,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Hook request doc required",
      "Hook request doc required detail={}"),
  HOOK_REQUEST_INVOCATION_EXCEPTION(
      1522,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Hook request invocation exception",
      "Hook request invocation exception detail={}"),
  HOOK_REQUEST_INVALID_TYPE(
      1523,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Hook request invalid type",
      "Hook request invalid type detail={}"),
  HOOK_REQUEST_RESPONSE_EXCEPTION(
      1524,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Hook request response exception",
      "Hook request response exception detail={}"),
  HOOK_REQUEST_RESPONSE_NULL(
      1525,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Hook request response null",
      "Hook request response null detail={}"),
  INVALID_BRAND_CODE(
      1526,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid brand code",
      "Invalid brand code detail={}"),
  PRODUCT_EXPIRED(
      1527,
      true,
      AuditEventType.OTHER,
      AuditOutcome.FAILURE,
      "Product license expired",
      "Product expired detail={}"),
  RCONSOLE_SRVCONFIG_REQD_FOR_MAILTO(
      1528,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole srvconfig reqd for mailto",
      "Rconsole srvconfig reqd for mailto detail={}"),
  RCONSOLE_NOTIFIER_REQD_FOR_MAILTO(
      1529,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole notifier reqd for mailto",
      "Rconsole notifier reqd for mailto detail={}"),
  RCONSOLE_NOTIFIER_HOST_REQD_FOR_MAILTO(
      1530,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole notifier host reqd for mailto",
      "Rconsole notifier host reqd for mailto detail={}"),
  RCONSOLE_NOTIFIER_FROM_REQD_FOR_MAILTO(
      1531,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole notifier from reqd for mailto",
      "Rconsole notifier from reqd for mailto detail={}"),
  RCONSOLE_CACHE_FLUSHED(
      1532,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole cache flushed",
      "Rconsole cache flushed detail={}"),
  RCONSOLE_CACHE_STARTED(
      1533,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole cache started",
      "Rconsole cache started detail={}"),
  RCONSOLE_CACHE_STOPPED(
      1534,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole cache stopped",
      "Rconsole cache stopped detail={}"),
  RCONSOLE_CACHE_ALREADY_STOPPED(
      1535,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole cache already stopped",
      "Rconsole cache already stopped detail={}"),
  RCONSOLE_CACHE_RESTARTED(
      1536,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole cache restarted",
      "Rconsole cache restarted detail={}"),
  INSUFFICIENT_NUM_CACHE_KEYS(
      1537,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Insufficient num cache keys",
      "Insufficient num cache keys detail={}"),
  MISSING_CACHE_KEY(
      1538,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Missing cache key",
      "Missing cache key detail={}"),
  INVALID_NUMBER_CACHE_KEY(
      1539,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid number cache key",
      "Invalid number cache key detail={}"),
  INVALID_REVISION_CACHE_KEY(
      1540,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Invalid revision cache key",
      "Invalid revision cache key detail={}"),
  RCONSOLE_UNABLE_TO_EXECUTE_CACHE_COMMAND(
      1541,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole unable to execute cache command",
      "Rconsole unable to execute cache command detail={}"),
  RCONSOLE_I18NRESOURCES_RELOADED(
      1542,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole i18nresources reloaded",
      "Rconsole i18nresources reloaded detail={}"),
  RCONSOLE_DEBUG_SETTING(
      1543,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole debug setting",
      "Rconsole debug setting detail={}"),
  RCONSOLE_DEBUGMODE_REQD(
      1544,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole debugmode reqd",
      "Rconsole debugmode reqd detail={}"),
  RCONSOLE_SUCCESS(
      1545,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole success",
      "Rconsole success detail={}"),
  RCONSOLE_REQUIRES_CONTENTID(
      1546,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole requires contentid",
      "Rconsole requires contentid detail={}"),
  RCONSOLE_COMMAND_CANT_RUN(
      1547,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole command cant run",
      "Rconsole command cant run detail={}"),
  RCONSOLE_CONTENT_TYPES_PROCESSED(
      1548,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole content types processed",
      "Rconsole content types processed detail={}"),
  RCONSOLE_FTS_DISABLED(
      1549,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole fts disabled",
      "Rconsole fts disabled detail={}"),
  RCONSOLE_ITEMS_INDEXED(
      1550,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole items indexed",
      "Rconsole items indexed detail={}"),
  RCONSOLE_ITEMS_INDEXED_INVALID_CTYPES(
      1551,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole items indexed invalid ctypes",
      "Rconsole items indexed invalid ctypes detail={}"),
  CANNOT_FIND_CACHED_ITEMSUMMARY(
      1552,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cannot find cached itemsummary",
      "Cannot find cached itemsummary detail={}"),
  CANNOT_FIND_CACHED_FOLDER_RELATIONSHIP(
      1553,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Cannot find cached folder relationship",
      "Cannot find cached folder relationship detail={}"),
  RCONSOLE_FOLDERCACHE_FLUSHED(
      1554,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole foldercache flushed",
      "Rconsole foldercache flushed detail={}"),
  RCONSOLE_SEARCH_QUEUE_CLEARED(
      1555,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Rconsole search queue cleared",
      "Rconsole search queue cleared detail={}"),
  CE_MISSING_CONTROL_NAME(
      1601,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing control name",
      "Ce missing control name detail={}"),
  CE_MISSING_FIELDSET(
      1602,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing fieldset",
      "Ce missing fieldset detail={}"),
  CE_MISSING_REQUESTOR(
      1603,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing requestor",
      "Ce missing requestor detail={}"),
  CE_MISSING_FORMACTION(
      1604,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing formaction",
      "Ce missing formaction detail={}"),
  CE_UNSUPPORTED_MAPPING_TYPE(
      1605,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce unsupported mapping type",
      "Ce unsupported mapping type detail={}"),
  CE_MISSING_MAPPINGS(
      1606,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing mappings",
      "Ce missing mappings detail={}"),
  CE_MISSING_FIELD(
      1607,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing field",
      "Ce missing field detail={}"),
  CE_MISSING_RESULTSET(
      1608,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing resultset",
      "Ce missing resultset detail={}"),
  CE_SQL_ERRORS(
      1609,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce sql errors",
      "Ce sql errors detail={}"),
  CE_MISSING_PAGEMAP(
      1610,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing pagemap",
      "Ce missing pagemap detail={}"),
  CE_MISSING_CHILDMAPPER(
      1611,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing childmapper",
      "Ce missing childmapper detail={}"),
  CE_MISSING_PAGEMAP_ENTRY(
      1612,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing pagemap entry",
      "Ce missing pagemap entry detail={}"),
  CE_NO_DATA_IN_RESULT_SET(
      1613,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce no data in result set",
      "Ce no data in result set detail={}"),
  CE_BAD_NUMBER_FORMAT(
      1614,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce bad number format",
      "Ce bad number format detail={}"),
  CE_INVALID_PAGEID(
      1615,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce invalid pageid",
      "Ce invalid pageid detail={}"),
  CE_AMBIGUOUS_PAGEID(
      1616,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce ambiguous pageid",
      "Ce ambiguous pageid detail={}"),
  CE_NO_PARENT(
      1617,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce no parent",
      "Ce no parent detail={}"),
  CE_MULTIPLE_TABLES_NOT_SUPPORTED(
      1618,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce multiple tables not supported",
      "Ce multiple tables not supported detail={}"),
  CE_UNSUPPORTED_MERGER(
      1619,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce unsupported merger",
      "Ce unsupported merger detail={}"),
  CE_MISSING_TABLE(
      1620,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing table",
      "Ce missing table detail={}"),
  CE_BACKEND_COL_REQUIRED(
      1621,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce backend col required",
      "Ce backend col required detail={}"),
  CE_MISSING_CHOICESET(
      1624,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing choiceset",
      "Ce missing choiceset detail={}"),
  CE_CHOICESET_NOT_SUPPORTED(
      1625,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce choiceset not supported",
      "Ce choiceset not supported detail={}"),
  CE_MODIFY_INVALID_PARAM(
      1626,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce modify invalid param",
      "Ce modify invalid param detail={}"),
  CE_EXCLUDED_SYSTEM_FIELD_MAPPED(
      1627,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce excluded system field mapped",
      "Ce excluded system field mapped detail={}"),
  CE_INVALID_PARAM(
      1628,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce invalid param",
      "Ce invalid param detail={}"),
  CE_CANT_PREVIEW_NEWDOC(
      1629,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce cant preview newdoc",
      "Ce cant preview newdoc detail={}"),
  CE_MODIFY_VALIDATION_FAIL(
      1632,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce modify validation fail",
      "Ce modify validation fail detail={}"),
  CE_MODIFY_VALIDATION_NO_ROWS(
      1633,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce modify validation no rows",
      "Ce modify validation no rows detail={}"),
  CE_MODIFY_VALIDATION_EXCEPTION(
      1634,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce modify validation exception",
      "Ce modify validation exception detail={}"),
  CE_INVALID_CHOICES_LOOKUP_EXTENSION(
      1635,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce invalid choices lookup extension",
      "Ce invalid choices lookup extension detail={}"),
  CE_CHOICES_LOOKUP_EXTENSION_NOT_FOUND(
      1636,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce choices lookup extension not found",
      "Ce choices lookup extension not found detail={}"),
  CE_COPY_REVISION_NOT_FOUND(
      1637,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce copy revision not found",
      "Ce copy revision not found detail={}"),
  CE_MISSING_REDIRECTS(
      1638,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing redirects",
      "Ce missing redirects detail={}"),
  CE_NO_REDIRECT_URL(
      1639,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce no redirect url",
      "Ce no redirect url detail={}"),
  CE_MODIFY_VALIDATION_FAIL_NOT_CHECKOUT(
      1640,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce modify validation fail not checkout",
      "Ce modify validation fail not checkout detail={}"),
  CE_MISSING_TABLE_NAME(
      1641,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing table name",
      "Ce missing table name detail={}"),
  CE_VIEW_SET_MISSING(
      1644,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce view set missing",
      "Ce view set missing detail={}"),
  CE_SYSTEM_DEF_INVALID(
      1676,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce system def invalid",
      "Ce system def invalid detail={}"),
  CE_SHARED_DEF_INVALID(
      1677,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce shared def invalid",
      "Ce shared def invalid detail={}"),
  CE_TABLE_ALIAS_DUPLICATE(
      1678,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce table alias duplicate",
      "Ce table alias duplicate detail={}"),
  CE_MISSING_CREDENTIALS(
      1685,
      true,
      AuditEventType.AUTH_FAILURE,
      AuditOutcome.FAILURE,
      "Missing credentials for content editor",
      "Content editor missing credentials resource={}"),
  CE_INVALID_CHOICES_LOOKUP_URL(
      1686,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce invalid choices lookup url",
      "Ce invalid choices lookup url detail={}"),
  CE_DUPLICATE_SUBMIT_NAME(
      1687,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce duplicate submit name",
      "Ce duplicate submit name detail={}"),
  CE_NEEDED_APP_NOT_RUNNING(
      1688,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce needed app not running",
      "Ce needed app not running detail={}"),
  CE_MISSING_CONTROL(
      1689,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce missing control",
      "Ce missing control detail={}"),
  CE_FIELD_NOT_DISPLAYED(
      1690,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce field not displayed",
      "Ce field not displayed detail={}"),
  CE_DEFAULT_WF_EXCLUDED(
      1691,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce default wf excluded",
      "Ce default wf excluded detail={}"),
  CE_DEFAULT_WF_NOT_INLUDED(
      1692,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce default wf not inluded",
      "Ce default wf not inluded detail={}"),
  CE_DUPLICATE_FIELD_NAME_ERROR(
      1693,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce duplicate field name error",
      "Ce duplicate field name error detail={}"),
  CE_DUPLICATE_FIELD_NAME_WARNING(
      1694,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce duplicate field name warning",
      "Ce duplicate field name warning detail={}"),
  CE_DUPLICATE_CHOICES(
      1695,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce duplicate choices",
      "Ce duplicate choices detail={}"),
  CE_MODIFY_VALIDATION_FAIL_OLD_EDITREVISION(
      1696,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce modify validation fail old editrevision",
      "Ce modify validation fail old editrevision detail={}"),
  COMPARE_CONTENTID_REQUIRED(
      1697,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Compare contentid required",
      "Compare contentid required detail={}"),
  COMPARE_VARIANTID_REQUIRED(
      1698,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Compare variantid required",
      "Compare variantid required detail={}"),
  COMPARE_REVISION_REQUIRED(
      1699,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Compare revision required",
      "Compare revision required detail={}"),
  COMPARE_HTTP_CONNECTION_ERROR(
      1700,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Compare http connection error",
      "Compare http connection error detail={}"),
  COMPARE_IREQ_CANNOTBE_NULL(
      1701,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Compare ireq cannotbe null",
      "Compare ireq cannotbe null detail={}"),
  COMPARE_IREQ_CALL_EXCEPTION(
      1702,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Compare ireq call exception",
      "Compare ireq call exception detail={}"),
  COMPARE_ASSEMBLY_URL_EMPTY(
      1703,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Compare assembly url empty",
      "Compare assembly url empty detail={}"),
  COMPARE_MALLFORMED_URL_ERROR(
      1704,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Compare mallformed url error",
      "Compare mallformed url error detail={}"),
  COMPARE_DOCURUN_INITIALIZATION_ERROR(
      1705,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Compare docurun initialization error",
      "Compare docurun initialization error detail={}"),
  COMPARE_DOCURUN_COMPARE_ERROR(
      1706,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Compare docurun compare error",
      "Compare docurun compare error detail={}"),
  CE_DUPLICATE_COL_NAME_WARNING(
      1707,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Ce duplicate col name warning",
      "Ce duplicate col name warning detail={}"),
  FIELD_TRANSFORM_ERROR(
      1708,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Field transform error",
      "Field transform error detail={}"),
  NORUN_NAMESPACE_CLEANUP_WARNING(
      1709,
      false,
      null,
      AuditOutcome.UNKNOWN,
      "Norun namespace cleanup warning",
      "Norun namespace cleanup warning detail={}");

  private final int numericCode;
  private final boolean auditable;
  private final AuditEventType eventType;
  private final AuditOutcome defaultOutcome;
  private final String userMessageTemplate;
  private final String logMessageTemplate;

  ServerErrorCodes(
      int numericCode,
      boolean auditable,
      AuditEventType eventType,
      AuditOutcome defaultOutcome,
      String userMessageTemplate,
      String logMessageTemplate) {
    this.numericCode = numericCode;
    this.auditable = auditable;
    this.eventType = eventType;
    this.defaultOutcome = defaultOutcome;
    this.userMessageTemplate = userMessageTemplate;
    this.logMessageTemplate = logMessageTemplate;
  }

  static {
    ensureRegistered();
  }

  /**
   * Register (or re-register) all constants in {@link LegacyErrorCodeRegistry}. Safe to call
   * repeatedly — used by registry bootstrap and tests after {@code clearForTests}.
   */
  public static void ensureRegistered() {
    for (ServerErrorCodes code : values()) {
      LegacyErrorCodeRegistry.register(code.numericCode(), code);
    }
  }


  @Override
  public AuditModule module() {
    return AuditModule.SYS;
  }

  @Override
  public int numericCode() {
    return numericCode;
  }

  @Override
  public String userMessageTemplate() {
    return userMessageTemplate;
  }

  @Override
  public String logMessageTemplate() {
    return logMessageTemplate;
  }

  @Override
  public boolean isAuditable() {
    return auditable;
  }

  @Override
  public AuditEventType eventType() {
    return eventType;
  }

  @Override
  public AuditOutcome defaultOutcome() {
    return defaultOutcome;
  }
}
