@echo off
REM hot-deploy-local.bat - Build selected CMS modules and copy outputs into a local install (Windows)
REM Usage: scripts\hot-deploy-local.bat --install-dir "C:\path\to\install" [--modules system,rest] [--skip-build] [--restart] [--with-tests] [--help]

setlocal EnableDelayedExpansion










































































































































































































































































exit /B 0endlocal)  echo Deploy complete. Restart Jetty to load updated classes/resources.) else (  call :restart_jettyif "%RESTART%"=="1" ()  )    exit /B 1    echo ERROR: Unsupported module '%%~M'. Allowed: system,rest,sitemanage,webui  ) else (    call :deploy_webui  ) else if /I "%%~M"=="webui" (    call :deploy_jar_module "projects\sitemanage" "sitemanage"  ) else if /I "%%~M"=="sitemanage" (    call :deploy_jar_module "rest" "rest"  ) else if /I "%%~M"=="rest" (    call :deploy_jar_module "system" "perc-system"  if /I "%%~M"=="system" (for %%M in (%MODULES%) do (REM Main dispatch: iterate over modules and call deploy functionsexit /B 0)  echo NOTICE: No StartJetty script found.) else (  )    echo NOTICE: No StartJetty.bat and no bash available. Start Jetty manually.  ) else (    popd >nul 2>&1    bash ./StartJetty.sh    pushd "%jetty_dir%" >nul 2>&1  if %ERRORLEVEL%==0 (  where bash >nul 2>&1) else if exist "%jetty_dir%\StartJetty.sh" (  popd >nul 2>&1  call "%start_script%"  pushd "%jetty_dir%" >nul 2>&1if exist "%start_script%" (echo Starting Jetty...if exist "%server_log%" del /f /q "%server_log%" >nul 2>&1 & echo Removed log file: %server_log%)  )    )      echo NOTICE: No StopJetty.bat and no bash available. Stop Jetty manually if needed.    ) else (      popd >nul 2>&1      bash ./StopJetty.sh      pushd "%jetty_dir%" >nul 2>&1      echo Stopping Jetty via bash StopJetty.sh...    if %ERRORLEVEL%==0 (    where bash >nul 2>&1  if exist "%jetty_dir%\StopJetty.sh" () else (  timeout /t 2 >nul  popd >nul 2>&1  call "%stop_script%"  pushd "%jetty_dir%" >nul 2>&1  echo Stopping Jetty...if exist "%stop_script%" (set "server_log=%JETTY_BASE_DIR%\logs\server.log"set "start_script=%jetty_dir%\StartJetty.bat"set "stop_script=%jetty_dir%\StopJetty.bat"set "jetty_dir=%INSTALL_DIR%\jetty":restart_jettyexit /B 0)  echo Synced common JS -> %WEB_RESOURCES_JS_DIR%  xcopy "%WEBAPP_DIR%\cm\common\js\*" "%WEB_RESOURCES_JS_DIR%\" /E /Y /I >nul  if not exist "%WEB_RESOURCES_JS_DIR%" mkdir "%WEB_RESOURCES_JS_DIR%"if exist "%WEBAPP_DIR%\cm\common\js\" (powershell -NoProfile -Command "Expand-Archive -Path '%war_path%' -DestinationPath '%WEBAPP_DIR%' -Force" >nul 2>&1echo Unzipping %war_path% -> %WEBAPP_DIR%)  exit /B 1  echo ERROR: Could not find built WAR in %target_dir%if "%war_path%"=="" (:war_found)  goto :war_found  set "war_path=%target_dir%\%%W"for /f "delims=" %%W in ('dir /b /a:-d /o:-d "%target_dir%\perc-web-ui-*.war" 2^>nul') do (set "war_path=")  exit /B 1  echo ERROR: target directory not found for WebUI: %target_dir%if not exist "%target_dir%" ()  popd >nul 2>&1  )    call mvn -pl "%module_path%" clean install %MVN_TEST_FLAG%  ) else (    call "%PROJECT_ROOT%\mvn-env.bat" -pl "%module_path%" clean install %MVN_TEST_FLAG%  if exist "%PROJECT_ROOT%\mvn-env.bat" (  pushd "%PROJECT_ROOT%" >nul 2>&1  echo Building WebUI...if "%SKIP_BUILD%"=="0" (set "target_dir=%PROJECT_ROOT%\%module_path%\target"set "module_path=WebUI":deploy_webuiexit /B 0echo Deployed %jar_name% -> %LIB_DIR%copy /Y "%jar_path%" "%LIB_DIR%\%jar_name%" >nul)  )    if /I not "%%~nxF"=="%jar_name%" del /q "%%~fF"  for %%F in ("%LIB_DIR%\%artifact_id%-*.jar") do (if exist "%LIB_DIR%\%artifact_id%-*.jar" (for %%F in ("%jar_path%") do set "jar_name=%%~nxF")  exit /B 1  echo ERROR: Could not find built jar for %artifact_id% in %target_dir%if "%jar_path%"=="" (:jar_found)  )    goto :jar_found    set "jar_path=%target_dir%\%%J"  echo %%J|findstr /i /c:"-sources" /c:"-javadoc" /c:"-tests" /c:"original" >nul || (for /f "delims=" %%J in ('dir /b /a:-d /o:-d "%target_dir%\%artifact_id%-*.jar" 2^>nul') do (set "jar_path=")  exit /B 1  echo ERROR: target directory not found for %module_path%: %target_dir%if not exist "%target_dir%" ()  popd >nul 2>&1  )    call mvn -pl "%module_path%" clean install %MVN_TEST_FLAG%  ) else (    call "%PROJECT_ROOT%\mvn-env.bat" -pl "%module_path%" clean install %MVN_TEST_FLAG%  if exist "%PROJECT_ROOT%\mvn-env.bat" (  pushd "%PROJECT_ROOT%" >nul 2>&1  echo Building module path: %module_path%if "%SKIP_BUILD%"=="0" (set "target_dir=%PROJECT_ROOT%\%module_path%\target"set "artifact_id=%~2"set "module_path=%~1":deploy_jar_moduleREM deploy_jar_module: %1=module_path, %2=artifact_idecho.echo Run tests    : %RUN_TESTS%echo Skip build   : %SKIP_BUILD%echo Modules      : %MODULES_CSV%echo Install dir  : %INSTALL_DIR%echo Project root : %PROJECT_ROOT%set "MODULES=%MODULES_CSV:,= %"REM Replace commas with spaces for simple iteration)  exit /B 1  echo ERROR: CMS lib directory not found: %LIB_DIR%if not exist "%LIB_DIR%" ()  exit /B 1  echo ERROR: Jetty base directory not found: %JETTY_BASE_DIR%if not exist "%JETTY_BASE_DIR%" (set "WEB_RESOURCES_JS_DIR=%INSTALL_DIR%\web_resources\cm\common\js"set "LIB_DIR=%WEBAPP_DIR%\WEB-INF\lib"set "WEBAPP_DIR=%JETTY_BASE_DIR%\webapps\Rhythmyx"set "JETTY_BASE_DIR=%INSTALL_DIR%\jetty\base")  set "MVN_TEST_FLAG=-DskipTests") else (  set "MVN_TEST_FLAG="if "%RUN_TESTS%"=="1" ()  exit /B 1  call :usage  echo ERROR: --install-dir is required.if "%INSTALL_DIR%"=="" (:after_parseexit /B 1call :usageecho Unknown option: %~1)  exit /B 0  call :usageif /I "%~1"=="--help" ()  goto parse_args  shift  set "RUN_TESTS=1"if /I "%~1"=="--with-tests" ()  goto parse_args  shift  set "RESTART=1"if /I "%~1"=="--restart" ()  goto parse_args  shift  set "SKIP_BUILD=1"if /I "%~1"=="--skip-build" ()  goto parse_args  shift  shift  set "MODULES_CSV=%~2"if /I "%~1"=="--modules" ()  goto parse_args  shift  shift  set "INSTALL_DIR=%~2"if /I "%~1"=="--install-dir" (if "%~1"=="" goto after_parse:parse_args
nREM Parse args)  for %%G in ("%SCRIPT_DIR%\..") do set "PROJECT_ROOT=%%~fG"  if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"  set "SCRIPT_DIR=%~dp0"if "%PROJECT_ROOT%"=="" (for /f "usebackq delims=" %%G in (`git rev-parse --show-toplevel 2^>nul`) do set "PROJECT_ROOT=%%G"
nREM Determine project root using git, fallback to script parent foldergoto :eofecho.echo   --help                   Show this help.echo   --with-tests             Run tests during Maven build (default is -DskipTests).echo   --restart                Restart local Jetty after deploy (StopJetty.bat + StartJetty.bat).echo   --skip-build             Skip Maven build and deploy existing artifacts from target\.echo                           Default: systemecho   --modules ^<list^>       Comma-separated modules: system,rest,sitemanage,webuiecho   --install-dir ^<path^>   CMS install directory (contains jetty\base). Required.echo Options:echo.echo   %~nx0 --install-dir ^<path^> [options]echo Usage:
n:usageset "MVN_TEST_FLAG=-DskipTests"set "RUN_TESTS=0"set "RESTART=0"set "SKIP_BUILD=0"set "MODULES_CSV=system"set "INSTALL_DIR="set "PROJECT_ROOT="REM may require PowerShell or Git Bash to be available on Windows.n
em NOTE: This is a best-effort CMD translation of the Linux shell script. Some operations (unzip, bash scripts)