/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.3 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.09.28 at 02:03:46 PM EDT
//

package com.percussion.pagemanagement.data;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.percussion.share.data.PSAbstractPersistantObject;
import jakarta.xml.bind.annotation.*;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Represents a widget definition, including preferences, resources, and content. Generated from
 * JAXB schema, modernized for Java 11 and Google Java Style.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {
      "id",
      "widgetPrefs",
      "resource",
      "dnDPref",
      "userPref",
      "cssPref",
      "code",
      "content"
    })
@XmlRootElement(name = "Widget")
@JsonRootName("Widget")
public class PSWidgetDefinition extends PSAbstractPersistantObject {

  private static final long serialVersionUID = 3560553163599331699L;

  private String id;

  @Override
  public String getId() {
    return id;
  }

  @Override
  public void setId(String id) {
    this.id = id;
  }

  @XmlElement(name = "WidgetPrefs")
  protected WidgetPrefs widgetPrefs;

  @XmlElement(name = "Resource")
  protected ArrayList<Resource> resource;

  @XmlElement(name = "DnDPref")
  protected ArrayList<DnDPref> dnDPref;

  @XmlElement(name = "UserPref")
  protected ArrayList<UserPref> userPref;

  @XmlElement(name = "CssPref")
  protected ArrayList<CssPref> cssPref;

  @XmlElement(name = "Content", required = true)
  protected Content content;

  @XmlElement(name = "Code", required = true)
  protected Code code;

  public Optional<WidgetPrefs> getWidgetPrefs() {
    return Optional.ofNullable(widgetPrefs);
  }

  public void setWidgetPrefs(WidgetPrefs value) {
    this.widgetPrefs = value;
  }

  public List<Resource> getResource() {
    if (resource == null) {
      resource = new ArrayList<>();
    }
    return resource;
  }

  public List<DnDPref> getDnDPref() {
    if (dnDPref == null) {
      dnDPref = new ArrayList<>();
    }
    return dnDPref;
  }

  public List<UserPref> getUserPref() {
    if (userPref == null) {
      userPref = new ArrayList<>();
    }
    return userPref;
  }

  public List<CssPref> getCssPref() {
    if (cssPref == null) {
      cssPref = new ArrayList<>();
    }
    return cssPref;
  }

  public Optional<Content> getContent() {
    return Optional.ofNullable(content);
  }

  public void setContent(Content value) {
    this.content = value;
  }

  public Optional<Code> getCode() {
    return Optional.ofNullable(code);
  }

  public void setCode(Code value) {
    this.code = value;
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;simpleContent>
   *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *       &lt;attribute name="type" default="jexl">
   *         &lt;simpleType>
   *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *             &lt;enumeration value="jexl"/>
   *           &lt;/restriction>
   *         &lt;/simpleType>
   *       &lt;/attribute>
   *     &lt;/extension>
   *   &lt;/simpleContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"value"})
  public static class Code implements Serializable {

    private static final long serialVersionUID = 1L;

    @XmlValue protected String value;
    @XmlAttribute protected String type;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is {@link String }
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is {@link String }
     */
    public void setValue(String value) {
      this.value = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     */
    public String getType() {
      if (type == null) {
        return "jexl";
      }
      return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     */
    public void setType(String value) {
      this.type = value;
    }
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;simpleContent>
   *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *       &lt;attribute name="type" default="velocity">
   *         &lt;simpleType>
   *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *             &lt;enumeration value="velocity"/>
   *           &lt;/restriction>
   *         &lt;/simpleType>
   *       &lt;/attribute>
   *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="view" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="preferred_height" type="{http://www.w3.org/2001/XMLSchema}integer" />
   *       &lt;attribute name="preferred_width" type="{http://www.w3.org/2001/XMLSchema}integer" />
   *     &lt;/extension>
   *   &lt;/simpleContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"value"})
  public static class Content implements Serializable {

    private static final long serialVersionUID = 1L;

    @XmlValue protected String value;
    @XmlAttribute protected String type;
    @XmlAttribute protected String href;
    @XmlAttribute protected String view;

    @XmlAttribute(name = "preferred_height")
    protected BigInteger preferredHeight;

    @XmlAttribute(name = "preferred_width")
    protected BigInteger preferredWidth;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is {@link String }
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is {@link String }
     */
    public void setValue(String value) {
      this.value = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     */
    public String getType() {
      if (type == null) {
        return "html";
      }
      return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     */
    public void setType(String value) {
      this.type = value;
    }

    /**
     * Gets the value of the href property.
     *
     * @return possible object is {@link String }
     */
    public String getHref() {
      return href;
    }

    /**
     * Sets the value of the href property.
     *
     * @param value allowed object is {@link String }
     */
    public void setHref(String value) {
      this.href = value;
    }

    /**
     * Gets the value of the view property.
     *
     * @return possible object is {@link String }
     */
    public String getView() {
      return view;
    }

    /**
     * Sets the value of the view property.
     *
     * @param value allowed object is {@link String }
     */
    public void setView(String value) {
      this.view = value;
    }

    /**
     * Gets the value of the preferredHeight property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getPreferredHeight() {
      return preferredHeight;
    }

    /**
     * Sets the value of the preferredHeight property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setPreferredHeight(BigInteger value) {
      this.preferredHeight = value;
    }

    /**
     * Gets the value of the preferredWidth property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getPreferredWidth() {
      return preferredWidth;
    }

    /**
     * Sets the value of the preferredWidth property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setPreferredWidth(BigInteger value) {
      this.preferredWidth = value;
    }
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;attribute name="acceptedTypes" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="action" default="replace">
   *         &lt;simpleType>
   *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *             &lt;enumeration value="replace"/>
   *             &lt;enumeration value="append"/>
   *           &lt;/restriction>
   *         &lt;/simpleType>
   *       &lt;/attribute>
   *       &lt;attribute name="sourceType" default="single">
   *         &lt;simpleType>
   *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *             &lt;enumeration value="single"/>
   *             &lt;enumeration value="multi"/>
   *           &lt;/restriction>
   *         &lt;/simpleType>
   *       &lt;/attribute>
   *       &lt;attribute name="owner" default="parent">
   *         &lt;simpleType>
   *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *             &lt;enumeration value="parent"/>
   *             &lt;enumeration value="asset"/>
   *           &lt;/restriction>
   *         &lt;/simpleType>
   *       &lt;/attribute>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "")
  public static class DnDPref {

    @XmlAttribute protected String acceptedTypes;
    @XmlAttribute protected String action;
    @XmlAttribute protected String sourceType;
    @XmlAttribute protected String owner;

    /**
     * Gets the value of the acceptedTypes property.
     *
     * @return possible object is {@link String }
     */
    public String getAcceptedTypes() {
      return acceptedTypes;
    }

    /**
     * Sets the value of the acceptedTypes property.
     *
     * @param value allowed object is {@link String }
     */
    public void setAcceptedTypes(String value) {
      this.acceptedTypes = value;
    }

    /**
     * Gets the value of the action property.
     *
     * @return possible object is {@link String }
     */
    public String getAction() {
      if (action == null) {
        return "replace";
      }
      return action;
    }

    /**
     * Sets the value of the action property.
     *
     * @param value allowed object is {@link String }
     */
    public void setAction(String value) {
      this.action = value;
    }

    /**
     * Gets the value of the sourceType property.
     *
     * @return possible object is {@link String }
     */
    public String getSourceType() {
      if (sourceType == null) {
        return "single";
      }
      return sourceType;
    }

    /**
     * Sets the value of the sourceType property.
     *
     * @param value allowed object is {@link String }
     */
    public void setSourceType(String value) {
      this.sourceType = value;
    }

    /**
     * Gets the value of the owner property.
     *
     * @return possible object is {@link String }
     */
    public String getOwner() {
      if (owner == null) {
        return "parent";
      }
      return owner;
    }

    /**
     * Sets the value of the owner property.
     *
     * @param value allowed object is {@link String }
     */
    public void setOwner(String value) {
      this.owner = value;
    }
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="EnumValue" maxOccurs="unbounded" minOccurs="0">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                 &lt;attribute name="display_value" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="display_name" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="default_value" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="datatype" default="string">
   *         &lt;simpleType>
   *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *             &lt;enumeration value="string"/>
   *             &lt;enumeration value="hidden"/>
   *             &lt;enumeration value="bool"/>
   *             &lt;enumeration value="enum"/>
   *             &lt;enumeration value="list"/>
   *             &lt;enumeration value="number"/>
   *           &lt;/restriction>
   *         &lt;/simpleType>
   *       &lt;/attribute>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "AbstractUserPref",
      propOrder = {"enumValue"})
  public abstract static class AbstractUserPref {

    @XmlElement(name = "EnumValue")
    protected List<EnumValue> enumValue;

    @XmlAttribute(required = true)
    protected String name;

    @XmlAttribute(name = "display_name")
    protected String displayName;

    @XmlAttribute(name = "default_value")
    protected String defaultValue;

    @XmlAttribute protected String required;
    @XmlAttribute protected String datatype;

    /**
     * Gets the value of the enumValue property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the enumValue property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getEnumValue().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link
     * PSWidgetDefinition.AbstractUserPref.EnumValue }
     *
     * @return never <code>null</code>.
     */
    public List<EnumValue> getEnumValue() {
      if (enumValue == null) {
        enumValue = new ArrayList<>();
      }
      return this.enumValue;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     */
    public String getName() {
      return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     */
    public void setName(String value) {
      this.name = value;
    }

    /**
     * Gets the value of the displayName property.
     *
     * @return possible object is {@link String }
     */
    public String getDisplayName() {
      return displayName;
    }

    /**
     * Sets the value of the displayName property.
     *
     * @param value allowed object is {@link String }
     */
    public void setDisplayName(String value) {
      this.displayName = value;
    }

    /**
     * Gets the value of the defaultValue property.
     *
     * @return default value, it may <code>null</code> if not defined.
     */
    public String getDefaultValue() {
      return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     *
     * @param value allowed object is {@link String }
     */
    public void setDefaultValue(String value) {
      this.defaultValue = value;
    }

    /**
     * Gets the value of the required property.
     *
     * @return possible object is {@link String }
     */
    public String getRequired() {
      return required;
    }

    /**
     * Sets the value of the required property.
     *
     * @param value allowed object is {@link String }
     */
    public void setRequired(String value) {
      this.required = value;
    }

    /**
     * Gets the value of the datatype property.
     *
     * @return possible object is {@link String }
     */
    public String getDatatype() {
      if (datatype == null) {
        return "string";
      }
      return datatype;
    }

    /**
     * Sets the value of the datatype property.
     *
     * @param value allowed object is {@link String }
     */
    public void setDatatype(String value) {
      this.datatype = value;
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="display_value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EnumValue {

      @XmlAttribute(required = true)
      protected String value;

      @XmlAttribute(name = "display_value")
      protected String displayValue;

      /**
       * Gets the value of the value property.
       *
       * @return possible object is {@link String }
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       *
       * @param value allowed object is {@link String }
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the displayValue property.
       *
       * @return possible object is {@link String }
       */
      public String getDisplayValue() {
        return displayValue;
      }

      /**
       * Sets the value of the displayValue property.
       *
       * @param value allowed object is {@link String }
       */
      public void setDisplayValue(String value) {
        this.displayValue = value;
      }
    }
  }

  public static class UserPref extends AbstractUserPref {}

  public static class CssPref extends AbstractUserPref {}

  /**
   * Represents an individual {@code Resource} element in the widget definition XML.
   *
   * <p>This nested type used to be generated from PSWidgetDefinition.xsd in earlier branches; it
   * was accidentally removed during refactoring and caused numerous "cannot find symbol Resource"
   * compile errors.
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "")
  public static class Resource {
    @XmlAttribute(required = true)
    protected String href;

    @XmlAttribute(required = true)
    protected String type;

    @XmlAttribute protected String placement;

    public String getHref() {
      return href;
    }

    public void setHref(String value) {
      this.href = value;
    }

    public String getType() {
      return type;
    }

    public void setType(String value) {
      this.type = value;
    }

    public String getPlacement() {
      if (placement == null) {
        return "head";
      }
      return placement;
    }

    public void setPlacement(String value) {
      this.placement = value;
    }
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;choice maxOccurs="unbounded" minOccurs="0">
   *         &lt;element name="Icon">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="mode">
   *                   &lt;simpleType>
   *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *                       &lt;enumeration value="base64"/>
   *                     &lt;/restriction>
   *                   &lt;/simpleType>
   *                 &lt;/attribute>
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/choice>
   *       &lt;attribute name="contenttype_name" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="title_url" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="author" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="author_email" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="screenshot" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="thumbnail" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="preferred_editor_height" type="{http://www.w3.org/2001/XMLSchema}integer" />
   *       &lt;attribute name="preferred_editor_width" type="{http://www.w3.org/2001/XMLSchema}integer" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"icon"})
  public static class WidgetPrefs implements Serializable {

    /**
     * Bumped from 1L when {@code icon} field type changed from {@code List} to {@code ArrayList}
     * and {@link #setIcon} was added (JAXB / serialization contract).
     */
    private static final long serialVersionUID = 2L;

    @XmlElement(name = "Icon")
    protected ArrayList<Icon> icon;

    @XmlAttribute(name = "contenttype_name")
    protected String contenttypeName;

    @XmlAttribute(name = "category")
    protected String category;

    @XmlAttribute protected String title;

    @XmlAttribute(name = "title_url")
    protected String titleUrl;

    @XmlAttribute protected String description;
    @XmlAttribute protected String author;

    @XmlAttribute(name = "author_email")
    protected String authorEmail;

    @XmlAttribute protected String screenshot;
    @XmlAttribute protected String thumbnail;

    @XmlAttribute(name = "preferred_editor_height")
    protected BigInteger preferredEditorHeight;

    @XmlAttribute(name = "preferred_editor_width")
    protected BigInteger preferredEditorWidth;

    @XmlAttribute(name = "create_shared_asset")
    protected Boolean createSharedAsset = Boolean.TRUE;

    @XmlAttribute(name = "is_editable_on_template")
    protected Boolean isEditableOnTemplate = Boolean.TRUE;

    @XmlAttribute(name = "is_responsive")
    protected Boolean isResponsive = Boolean.FALSE;

    /**
     * Gets the value of the icon property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. Callers may
     * also use {@link #setIcon(List)} (e.g. JAXB unmarshalling) to replace the list; that method
     * always stores a concrete {@link ArrayList}.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getIcon().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link
     * PSWidgetDefinition.WidgetPrefs.Icon }
     *
     * @return never <code>null</code>.
     */
    public List<Icon> getIcon() {
      if (icon == null) {
        icon = new ArrayList<>();
      }
      return icon;
    }

    /**
     * Sets the icon list (JAXB / callers). Any {@link List} is copied into a concrete {@link
     * ArrayList} for a stable serialization type.
     *
     * @param icon icon list, may be null
     */
    public void setIcon(List<Icon> icon) {
      this.icon = icon == null ? null : new ArrayList<>(icon);
    }

    /**
     * Gets the value of the contenttypeName property.
     *
     * @return possible object is {@link String }
     */
    public String getContenttypeName() {
      return contenttypeName;
    }

    /**
     * Sets the value of the contenttypeName property.
     *
     * @param value allowed object is {@link String }
     */
    public void setContenttypeName(String value) {
      this.contenttypeName = value;
    }

    /**
     * Gets the value of the category property.
     *
     * @return The category of the widget.
     */
    public String getCategory() {
      return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value allowed object is {@link String }
     */
    public void setCategory(String value) {
      this.category = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is {@link String }
     */
    public String getTitle() {
      return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTitle(String value) {
      this.title = value;
    }

    /**
     * Gets the value of the titleUrl property.
     *
     * @return possible object is {@link String }
     */
    public String getTitleUrl() {
      return titleUrl;
    }

    /**
     * Sets the value of the titleUrl property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTitleUrl(String value) {
      this.titleUrl = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     */
    public String getDescription() {
      return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is {@link String }
     */
    public void setDescription(String value) {
      this.description = value;
    }

    /**
     * Gets the value of the author property.
     *
     * @return possible object is {@link String }
     */
    public String getAuthor() {
      return author;
    }

    /**
     * Sets the value of the author property.
     *
     * @param value allowed object is {@link String }
     */
    public void setAuthor(String value) {
      this.author = value;
    }

    /**
     * Gets the value of the authorEmail property.
     *
     * @return possible object is {@link String }
     */
    public String getAuthorEmail() {
      return authorEmail;
    }

    /**
     * Sets the value of the authorEmail property.
     *
     * @param value allowed object is {@link String }
     */
    public void setAuthorEmail(String value) {
      this.authorEmail = value;
    }

    /**
     * Gets the value of the screenshot property.
     *
     * @return possible object is {@link String }
     */
    public String getScreenshot() {
      return screenshot;
    }

    /**
     * Sets the value of the screenshot property.
     *
     * @param value allowed object is {@link String }
     */
    public void setScreenshot(String value) {
      this.screenshot = value;
    }

    /**
     * Gets the value of the thumbnail property.
     *
     * @return possible object is {@link String }
     */
    public String getThumbnail() {
      return thumbnail;
    }

    /**
     * Sets the value of the thumbnail property.
     *
     * @param value allowed object is {@link String }
     */
    public void setThumbnail(String value) {
      this.thumbnail = value;
    }

    /**
     * Gets the value of the preferredHeight property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getPreferredEditorHeight() {
      return preferredEditorHeight;
    }

    /**
     * Sets the value of the preferredEditorHeight property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setPreferredEditorHeight(BigInteger value) {
      this.preferredEditorHeight = value;
    }

    /**
     * Gets the value of the preferredEditorWidth property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getPreferredEditorWidth() {
      return preferredEditorWidth;
    }

    /**
     * Sets the value of the preferredEditorWidth property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setPreferredEditorWidth(BigInteger value) {
      this.preferredEditorWidth = value;
    }

    /**
     * Gets the value of the createSharedAsset property.
     *
     * @return possible object is {@link Boolean}
     */
    public Boolean getCreateSharedAsset() {
      return createSharedAsset;
    }

    /**
     * Sets the value of the createSharedAsset property. If value is null then sets to TRUE
     *
     * @param value allowed object is {@link Boolean}
     */
    public void setCreateSharedAsset(Boolean value) {
      if (value == null) {
        value = Boolean.TRUE;
      }
      this.createSharedAsset = value;
    }

    /**
     * Gets the value of the isEditableOnTemplate property.
     *
     * @return possible object is {@link Boolean}
     */
    public Boolean getEditableOnTemplate() {
      return isEditableOnTemplate;
    }

    /**
     * Sets the value of the isEditableOnTemplate property If value is null sets to TRUE.
     *
     * @param value allowed object is {@link Boolean}
     */
    public void setEditableOnTemplate(Boolean value) {
      if (value == null) {
        value = Boolean.TRUE;
      }
      this.isEditableOnTemplate = value;
    }

    // setters for new properties

    public Boolean isResponsive() {
      return isResponsive;
    }

    public void setResponsive(Boolean isResponsive) {
      if (isResponsive != null) {
        isResponsive = Boolean.FALSE;
      }

      this.isResponsive = isResponsive;
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="mode">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="base64"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
        name = "",
        propOrder = {"value"})
    public static class Icon implements Serializable {

      private static final long serialVersionUID = 1L;

      @XmlValue protected String value;
      @XmlAttribute protected String mode;
      @XmlAttribute protected String type;

      /**
       * Gets the value of the value property.
       *
       * @return possible object is {@link String }
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       *
       * @param value allowed object is {@link String }
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the mode property.
       *
       * @return possible object is {@link String }
       */
      public String getMode() {
        return mode;
      }

      /**
       * Sets the value of the mode property.
       *
       * @param value allowed object is {@link String }
       */
      public void setMode(String value) {
        this.mode = value;
      }

      /**
       * Gets the value of the type property.
       *
       * @return possible object is {@link String }
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       *
       * @param value allowed object is {@link String }
       */
      public void setType(String value) {
        this.type = value;
      }
    }
  }
}
