/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.percussion.services.filestorage;

import java.io.IOException;
import java.io.InputStream;
import java.security.NoSuchAlgorithmException;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

/**
 * The file digest service generates unique hash values for file content using modern Java 11 patterns.
 *
 * <p>The hash values are generated using the algorithm specified by {@link #getAlgorithm()}.
 * This service provides both synchronous and asynchronous checksum generation with
 * Optional-based safe access and enhanced error handling.</p>
 *
 * @author peterfrontiero
 * @since 6.0
 */
public interface IPSFileDigestService {
   
   /**
    * Generates a checksum for the specified input stream and then closes the stream.
    *
    * <p>This method uses try-with-resources internally to ensure proper stream cleanup
    * even if an exception occurs during processing.</p>
    *
    * @param stream input stream representing the file content, never {@code null}
    * @return a unique checksum, never {@code null} or empty
    * @throws NoSuchAlgorithmException if the configured algorithm is not valid
    * @throws IOException if an error occurs reading from or closing the input stream
    * @throws IllegalArgumentException if stream is {@code null}
    */
   String createChecksum(InputStream stream) throws NoSuchAlgorithmException, IOException;

   /**
    * Generates a checksum for the specified input stream asynchronously.
    *
    * <p>This method provides non-blocking checksum generation for large files
    * or when processing multiple files concurrently. The input stream is
    * automatically closed when processing completes.</p>
    *
    * @param stream input stream representing the file content, never {@code null}
    * @return CompletableFuture that completes with the unique checksum
    */
   CompletableFuture<String> createChecksumAsync(InputStream stream);

   /**
    * Generates a checksum for the specified input stream with Optional wrapper for safe access.
    *
    * <p>This method catches all exceptions and returns an empty Optional if
    * checksum generation fails, providing a safe alternative to exception handling.</p>
    *
    * @param stream input stream representing the file content, never {@code null}
    * @return Optional containing the checksum, or empty if generation failed
    */
   Optional<String> createChecksumSafely(InputStream stream);

   /**
    * Gets the algorithm configured for checksum generation.
    *
    * <p>Currently returns "SHA1" for content addressing. This algorithm is used
    * for file deduplication purposes only and does not have security implications.</p>
    *
    * @return the algorithm name used for checksum generation, never {@code null}
    */
   String getAlgorithm();

   /**
    * Validates that the configured algorithm is available in the current JVM.
    *
    * @return {@code true} if the algorithm is available, {@code false} otherwise
    */
   default boolean isAlgorithmAvailable() {
      try {
         java.security.MessageDigest.getInstance(getAlgorithm());
         return true;
      } catch (NoSuchAlgorithmException e) {
         return false;
      }
   }

   /**
    * Gets the expected length of checksums generated by this service.
    *
    * <p>For SHA1, this typically returns 40 characters (160 bits as hex string).</p>
    *
    * @return the expected checksum length in characters
    */
   default int getChecksumLength() {
      return "SHA1".equals(getAlgorithm()) ? 40 : -1;
   }
}
