/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.21 at 04:40:48 PM EST 
//

package com.percussion.proxyconfig.service.impl;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"proxyConfigs"})
@XmlRootElement(name = "ProxyConfigurations")
public class ProxyConfigurations {
    @XmlElement(name = "ProxyConfig")
    protected List<ProxyConfig> proxyConfigs;

    /**
     * Gets the value of the proxyConfigs property. It holds all configurations
     * from the proxy configuration file.
     *
     * <p>This accessor method returns an immutable copy of the live list.</p>
     *
     * @return immutable list of ProxyConfig
     */
    public List<ProxyConfig> getConfigs() {
        return proxyConfigs == null ? List.of() : List.copyOf(proxyConfigs);
    }

    public void setConfigs(List<ProxyConfig> configs) {
        this.proxyConfigs = configs == null ? new ArrayList<>() : new ArrayList<>(configs);
    }
}
