// REFACTORED: CP-JAVA11
/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.08.24 at 01:24:36 PM EDT
//

package com.percussion.content.data;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import jakarta.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"field"})
@XmlRootElement(name = "AssetDef")
public class AssetDef {

  @XmlElement(name = "Field", required = true)
  protected List<AssetDef.Field> field;

  @XmlAttribute(required = true)
  protected String name;

  @XmlAttribute(required = true)
  protected String contentType;

  @XmlAttribute protected String targetStateName;

  /**
   * Gets the value of the field property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a set method for the field property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getField().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link AssetDef.Field }
   */
  public List<AssetDef.Field> getField() {
    if (field == null) {
      field = new ArrayList<>();
    }
    return field;
  }

  public String getName() {
    return name;
  }

  public void setName(String value) {
    this.name = value;
  }

  public String getContentType() {
    return contentType;
  }

  public void setContentType(String value) {
    this.contentType = value;
  }

  public String getTargetStateName() {
    return Optional.ofNullable(targetStateName).orElse("Draft");
  }

  public void setTargetStateName(String value) {
    this.targetStateName = value;
  }

  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"value"})
  public static class Field {

    @XmlValue
    @XmlSchemaType(name = "anySimpleType")
    protected Object value;

    @XmlAttribute(required = true)
    protected String name;

    @XmlAttribute protected String href;

    public Object getValue() {
      return value;
    }

    public void setValue(Object value) {
      this.value = value;
    }

    public String getName() {
      return name;
    }

    public void setName(String value) {
      this.name = value;
    }

    public String getHref() {
      return href;
    }

    public void setHref(String value) {
      this.href = value;
    }
  }
}
