// REFACTORED: CP-JAVA11
/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.12 at 02:47:07 PM ACT 
//


package com.percussion.content.data;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "siteDefs",
    "templateDefs",
    "sectionDefs",
    "assetFolder",
    "siteFolder",
    "autoGen"
})
@XmlRootElement(name = "CM1DataDef")
public class CM1DataDef {

    @XmlElement(name = "SiteDefs")
    protected CM1DataDef.SiteDefs siteDefs;
    @XmlElement(name = "TemplateDefs")
    protected CM1DataDef.TemplateDefs templateDefs;
    @XmlElement(name = "SectionDefs")
    protected List<CM1DataDef.SectionDefs> sectionDefs;
    @XmlElement(name = "AssetFolder")
    protected List<CM1DataDef.AssetFolder> assetFolder;
    @XmlElement(name = "SiteFolder")
    protected List<CM1DataDef.SiteFolder> siteFolder;
    @XmlElement(name = "AutoGen")
    protected CM1DataDef.AutoGen autoGen;

    public CM1DataDef.SiteDefs getSiteDefs() {
        return siteDefs;
    }

    public void setSiteDefs(CM1DataDef.SiteDefs value) {
        this.siteDefs = value;
    }

    public CM1DataDef.TemplateDefs getTemplateDefs() {
        return templateDefs;
    }

    public void setTemplateDefs(CM1DataDef.TemplateDefs value) {
        this.templateDefs = value;
    }

    public List<CM1DataDef.SectionDefs> getSectionDefs() {
        if (sectionDefs == null) {
            sectionDefs = new ArrayList<>();
        }
        return sectionDefs;
    }

    public List<CM1DataDef.AssetFolder> getAssetFolder() {
        if (assetFolder == null) {
            assetFolder = new ArrayList<>();
        }
        return assetFolder;
    }

    public List<CM1DataDef.SiteFolder> getSiteFolder() {
        if (siteFolder == null) {
            siteFolder = new ArrayList<>();
        }
        return siteFolder;
    }

    public CM1DataDef.AutoGen getAutoGen() {
        return autoGen;
    }

    public void setAutoGen(CM1DataDef.AutoGen value) {
        this.autoGen = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}AssetDef" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "assetDef"
    })
    public static class AssetFolder {

        @XmlElement(name = "AssetDef")
        protected List<AssetDef> assetDef;
        @XmlAttribute(required = true)
        protected String path;

        /**
         * Gets the value of the assetDef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the assetDef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssetDef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AssetDef }
         * 
         * 
         */
        public List<AssetDef> getAssetDef() {
            if (assetDef == null) {
                assetDef = new ArrayList<>();
            }
            return assetDef;
        }

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Folders" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="basePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
     *                 &lt;attribute name="maxDepth" type="{http://www.w3.org/2001/XMLSchema}int" default="10" />
     *                 &lt;attribute name="breadthFactor" type="{http://www.w3.org/2001/XMLSchema}float" default=".5" />
     *                 &lt;attribute name="baseNames" type="{http://www.w3.org/2001/XMLSchema}string" default="folder" />
     *                 &lt;attribute name="type" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *                       &lt;enumeration value="Assets"/>
     *                       &lt;enumeration value="Sites"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Assets" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AssetGroup" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="AssetDefName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="basePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Pages" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PageGroup" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="PageDefName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="basePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="basePath" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "folders",
        "assets",
        "pages"
    })
    public static class AutoGen {

        @XmlElement(name = "Folders")
        protected List<CM1DataDef.AutoGen.Folders> folders;
        @XmlElement(name = "Assets")
        protected List<CM1DataDef.AutoGen.Assets> assets;
        @XmlElement(name = "Pages")
        protected List<CM1DataDef.AutoGen.Pages> pages;
        @XmlAttribute
        protected String basePath;

        /**
         * Gets the value of the folders property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the folders property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFolders().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CM1DataDef.AutoGen.Folders }
         * 
         * 
         */
        public List<CM1DataDef.AutoGen.Folders> getFolders() {
            if (folders == null) {
                folders = new ArrayList<>();
            }
            return folders;
        }

        /**
         * Gets the value of the assets property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the assets property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssets().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CM1DataDef.AutoGen.Assets }
         * 
         * 
         */
        public List<CM1DataDef.AutoGen.Assets> getAssets() {
            if (assets == null) {
                assets = new ArrayList<>();
            }
            return assets;
        }

        /**
         * Gets the value of the pages property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pages property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPages().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CM1DataDef.AutoGen.Pages }
         * 
         * 
         */
        public List<CM1DataDef.AutoGen.Pages> getPages() {
            if (pages == null) {
                pages = new ArrayList<>();
            }
            return pages;
        }

        /**
         * Gets the value of the basePath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBasePath() {
            return basePath;
        }

        /**
         * Sets the value of the basePath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBasePath(String value) {
            this.basePath = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AssetGroup" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="AssetDefName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="basePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "assetGroup"
        })
        public static class Assets {

            @XmlElement(name = "AssetGroup")
            protected List<CM1DataDef.AutoGen.Assets.AssetGroup> assetGroup;
            @XmlAttribute(required = true)
            protected String basePath;
            @XmlAttribute
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger count;

            /**
             * Gets the value of the assetGroup property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the assetGroup property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAssetGroup().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CM1DataDef.AutoGen.Assets.AssetGroup }
             * 
             * 
             */
            public List<CM1DataDef.AutoGen.Assets.AssetGroup> getAssetGroup() {
                if (assetGroup == null) {
                    assetGroup = new ArrayList<>();
                }
                return assetGroup;
            }

            /**
             * Gets the value of the basePath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBasePath() {
                return basePath;
            }

            /**
             * Sets the value of the basePath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBasePath(String value) {
                this.basePath = value;
            }

            /**
             * Gets the value of the count property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCount() {
                if (count == null) {
                    return new BigInteger("1");
                } else {
                    return count;
                }
            }

            /**
             * Sets the value of the count property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCount(BigInteger value) {
                this.count = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="AssetDefName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "assetDefName"
            })
            public static class AssetGroup {

                @XmlElement(name = "AssetDefName", required = true)
                protected List<String> assetDefName;
                @XmlAttribute
                @XmlSchemaType(name = "positiveInteger")
                protected BigInteger count;

                /**
                 * Gets the value of the assetDefName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the assetDefName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAssetDefName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getAssetDefName() {
                    if (assetDefName == null) {
                        assetDefName = new ArrayList<>();
                    }
                    return assetDefName;
                }

                /**
                 * Gets the value of the count property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getCount() {
                    if (count == null) {
                        return new BigInteger("10");
                    } else {
                        return count;
                    }
                }

                /**
                 * Sets the value of the count property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setCount(BigInteger value) {
                    this.count = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Folders" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="basePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
         *                 &lt;attribute name="maxDepth" type="{http://www.w3.org/2001/XMLSchema}int" default="10" />
         *                 &lt;attribute name="breadthFactor" type="{http://www.w3.org/2001/XMLSchema}float" default=".5" />
         *                 &lt;attribute name="baseNames" type="{http://www.w3.org/2001/XMLSchema}string" default="folder" />
         *                 &lt;attribute name="type" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
         *                       &lt;enumeration value="Assets"/>
         *                       &lt;enumeration value="Sites"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Assets" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="AssetGroup" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="AssetDefName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="basePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Pages" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="PageGroup" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="PageDefName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="basePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>

