// REFACTORED: CP-JAVA11
/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.08.24 at 01:24:36 PM EDT
//

package com.percussion.content.data;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

  public ObjectFactory() {}

  public CM1DataDef.AutoGen.Folders createCM1DataDefAutoGenFolders() {
    return new CM1DataDef.AutoGen.Folders();
  }

  public CM1DataDef.AutoGen.Assets createCM1DataDefAutoGenAssets() {
    return new CM1DataDef.AutoGen.Assets();
  }

  public CM1DataDef.SiteDefs createCM1DataDefSiteDefs() {
    return new CM1DataDef.SiteDefs();
  }

  public CM1DataDef createCM1DataDef() {
    return new CM1DataDef();
  }

  public CM1DataDef.TemplateDefs createCM1DataDefTemplateDefs() {
    return new CM1DataDef.TemplateDefs();
  }

  public TemplateDef createTemplateDef() {
    return new TemplateDef();
  }

  public CM1DataDef.AutoGen.Pages createCM1DataDefAutoGenPages() {
    return new CM1DataDef.AutoGen.Pages();
  }

  public CM1DataDef.SiteFolder.PageDef createCM1DataDefSiteFolderPageDef() {
    return new CM1DataDef.SiteFolder.PageDef();
  }

  public CM1DataDef.AutoGen.Pages.PageGroup createCM1DataDefAutoGenPagesPageGroup() {
    return new CM1DataDef.AutoGen.Pages.PageGroup();
  }

  public AssetDef.Field createAssetDefField() {
    return new AssetDef.Field();
  }

  public CM1DataDef.SectionDefs.SectionDef createCM1DataDefSectionDefsSectionDef() {
    return new CM1DataDef.SectionDefs.SectionDef();
  }

  public CM1DataDef.SiteDefs.SiteDef createCM1DataDefSiteDefsSiteDef() {
    return new CM1DataDef.SiteDefs.SiteDef();
  }

  public CM1DataDef.SiteFolder createCM1DataDefSiteFolder() {
    return new CM1DataDef.SiteFolder();
  }

  public CM1DataDef.SectionDefs createCM1DataDefSectionDefs() {
    return new CM1DataDef.SectionDefs();
  }

  public CM1DataDef.AutoGen.Assets.AssetGroup createCM1DataDefAutoGenAssetsAssetGroup() {
    return new CM1DataDef.AutoGen.Assets.AssetGroup();
  }

  public TemplateDef.RegionDef createTemplateDefRegionDef() {
    return new TemplateDef.RegionDef();
  }

  public CM1DataDef.AutoGen createCM1DataDefAutoGen() {
    return new CM1DataDef.AutoGen();
  }

  public CM1DataDef.AssetFolder createCM1DataDefAssetFolder() {
    return new CM1DataDef.AssetFolder();
  }

  public AssetDef createAssetDef() {
    return new AssetDef();
  }

  public Widget createWidget() {
    return new Widget();
  }
}
