// REFACTORED: CP-JAVA11
/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.24 at 01:24:36 PM EDT 
//


package com.percussion.content.data;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bodyMarkup",
    "cssOverride",
    "additionalHeadContent",
    "afterBodyStart",
    "beforeBodyClose",
    "regionDef",
    "widget"
})
@XmlRootElement(name = "TemplateDef")
public class TemplateDef {

    @XmlElement(name = "BodyMarkup")
    protected String bodyMarkup;
    @XmlElement(name = "CssOverride")
    protected String cssOverride;
    @XmlElement(name = "AdditionalHeadContent")
    protected String additionalHeadContent;
    @XmlElement(name = "AfterBodyStart")
    protected String afterBodyStart;
    @XmlElement(name = "BeforeBodyClose")
    protected String beforeBodyClose;
    @XmlElement(name = "RegionDef")
    protected TemplateDef.RegionDef regionDef;
    @XmlElement(name = "Widget")
    protected List<Widget> widget;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String label;
    @XmlAttribute
    protected String siteName;
    @XmlAttribute(required = true)
    protected String baseTemplateName;

    public String getBodyMarkup() {
        return bodyMarkup;
    }

    public void setBodyMarkup(String value) {
        this.bodyMarkup = value;
    }

    public String getCssOverride() {
        return cssOverride;
    }

    public void setCssOverride(String value) {
        this.cssOverride = value;
    }

    public String getAdditionalHeadContent() {
        return additionalHeadContent;
    }

    public void setAdditionalHeadContent(String value) {
        this.additionalHeadContent = value;
    }

    public String getAfterBodyStart() {
        return afterBodyStart;
    }

    public void setAfterBodyStart(String value) {
        this.afterBodyStart = value;
    }

    public String getBeforeBodyClose() {
        return beforeBodyClose;
    }

    public void setBeforeBodyClose(String value) {
        this.beforeBodyClose = value;
    }

    public TemplateDef.RegionDef getRegionDef() {
        return regionDef;
    }

    public void setRegionDef(TemplateDef.RegionDef value) {
        this.regionDef = value;
    }

    public List<Widget> getWidget() {
        if (widget == null) {
            widget = new ArrayList<>();
        }
        return widget;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String value) {
        this.label = value;
    }

    public String getSiteName() {
        return siteName;
    }

    public void setSiteName(String value) {
        this.siteName = value;
    }

    public String getBaseTemplateName() {
        return baseTemplateName;
    }

    public void setBaseTemplateName(String value) {
        this.baseTemplateName = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RegionDef {

        @XmlAttribute(required = true)
        protected String name;
        @XmlAttribute
        protected String parentRegion;

        public String getName() {
            return name;
        }

        public void setName(String value) {
            this.name = value;
        }

        public String getParentRegion() {
            return parentRegion;
        }

        public void setParentRegion(String value) {
            this.parentRegion = value;
        }
    }
}
