// REFACTORED: CP-JAVA11
/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.24 at 01:24:36 PM EDT 
//


package com.percussion.content.data;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assetDef"
})
@XmlRootElement(name = "Widget")
public class Widget {

    @XmlElement(name = "AssetDef")
    protected AssetDef assetDef;
    @XmlAttribute(required = true)
    protected String widgetName;
    @XmlAttribute(required = true)
    protected String regionName;
    @XmlAttribute
    @XmlJavaTypeAdapter(javax.xml.bind.annotation.adapters.CollapsedStringAdapter.class)
    protected String contentSource;
    @XmlAttribute
    protected String sourceAssetName;

    public AssetDef getAssetDef() {
        return assetDef;
    }

    public void setAssetDef(AssetDef value) {
        this.assetDef = value;
    }

    public String getWidgetName() {
        return widgetName;
    }

    public void setWidgetName(String value) {
        this.widgetName = value;
    }

    public String getRegionName() {
        return regionName;
    }

    public void setRegionName(String value) {
        this.regionName = value;
    }

    public String getContentSource() {
        return java.util.Optional.ofNullable(contentSource).orElse("shared");
    }

    public void setContentSource(String value) {
        this.contentSource = value;
    }

    public String getSourceAssetName() {
        return sourceAssetName;
    }

    public void setSourceAssetName(String value) {
        this.sourceAssetName = value;
    }
}
