/*
 * Copyright 1999-2025 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// REFACTORED: CP-JAVA11

package com.percussion.assetmanagement.forms.service.impl;

import java.io.IOException;
import java.io.StringReader;
import java.io.StringWriter;
import java.util.*;

import org.apache.commons.lang.StringUtils;
import org.supercsv.io.CsvMapReader;
import org.supercsv.io.CsvMapWriter;
import org.supercsv.io.ICsvMapReader;
import org.supercsv.io.ICsvMapWriter;
import org.supercsv.prefs.CsvPreference;

/**
 * Merges the content of 0 or more CSV files (each with a header and 0 or more rows of data)
 * into a single CSV file, with a single header and a row for every row of data in the source
 * data. Handles the case where different files have different headers by putting empty data
 * for each row's cell if that row did not originally have that field's data. The output
 * rows are in the same order as the input rows.
 */
public class PSFormDataJoiner {

    private static final String FORM_NAME_FIELD = "Form name";
    private static final String CREATE_DATE_FIELD = "Create date";

    /**
     * Adds all columns in a form header into a Set of column names.
     *
     * @param columnNames Set where form headers will be added. Not {@code null}.
     * @param formHeader Array with form's header (column names). Not {@code null}.
     */
    private void addColumnNames(Set<CaselessString> columnNames, String[] formHeader) {
        for (var header : formHeader) {
            if (!FORM_NAME_FIELD.equals(header) && !CREATE_DATE_FIELD.equals(header)) {
                columnNames.add(new CaselessString(header));
            }
        }
    }

    /**
     * Prepares the final header to be written to a CSV file.
     *
     * @param columnsHeader The header with all the fields of every form, except
     *                      the 'form name' and 'create date'. Not {@code null}.
     * @return List with all the header columns, plus the 'form name' and 'create date' fields.
     */
    private List<CaselessString> prepareHeader(SortedSet<CaselessString> columnsHeader) {
        var finalHeader = new ArrayList<>(columnsHeader);
        // Add "form name" and "create date" fields at the beginning
        finalHeader.add(0, new CaselessString(CREATE_DATE_FIELD));
        finalHeader.add(0, new CaselessString(FORM_NAME_FIELD));
        return finalHeader;
    }

    /**
     * Takes a Map generated by SuperCSV and returns a new one, but with all
     * its keys normalized (using CaselessString class).
     *
     * @param csvRow Map generated with SuperCSV. Represents a row, with
     *               the header columns as keys. Not {@code null}.
     * @return a new Map with the same information, but using CaselessString as the key.
     */
    private Map<CaselessString, String> processCsvRow(Map<String, String> csvRow) {
        var processedRow = new HashMap<CaselessString, String>();
        for (var key : csvRow.keySet()) {
            processedRow.put(new CaselessString(key), csvRow.get(key));
        }
        return processedRow;
    }

    /**
     * Parses the raw data of the forms.
     *
     * @param data Raw data of forms. Not {@code null}.
     * @return Parsing result. Has the final header in alpha order and the data as a list of maps.
     */
    private ParsingResult parseCSVData(String[] data) {
        var finalHeaderSet = new TreeSet<CaselessString>();
        var currentDataList = new ArrayList<Map<CaselessString, String>>();
        Map<String, String> currentCsvData;
        ICsvMapReader reader = null;
        String[] formHeader;

        try {
            // First get all columns and store csv data in 'currentDataList'
            for (var datum : data) {
                if (datum == null || datum.isEmpty()) {
                    continue;
                }
                reader = new CsvMapReader(new StringReader(datum), CsvPreference.EXCEL_PREFERENCE);
                formHeader = reader.getHeader(true);
                addColumnNames(finalHeaderSet, formHeader);

                while ((currentCsvData = reader.read(formHeader)) != null) {
                    currentDataList.add(processCsvRow(currentCsvData));
                }
                reader.close();
            }
        } catch (IOException e) {
            // Should never happen since using string
            throw new RuntimeException("Unexpected IOException on String", e);
        }

        if (currentDataList.isEmpty()) {
            return new ParsingResult();
        }

        var finalCsvRowList = new ArrayList<Map<String, String>>();
        var finalHeader = this.prepareHeader(finalHeaderSet);

        for (var aCsvRow : currentDataList) {
            var aFinalCsvRow = new HashMap<String, String>();
            for (var aHeader : finalHeader) {
                // If this row has no data for aHeader, add a blank value
                aFinalCsvRow.put(aHeader.toString(), aCsvRow.getOrDefault(aHeader, StringUtils.EMPTY));
            }
            finalCsvRowList.add(aFinalCsvRow);
        }

        return new ParsingResult(finalHeader, finalCsvRowList);
    }

    /**
     * Writes a CSV file with the given header and data.
     *
     * @param parsingResult Result of parsing raw form data. Not {@code null}.
     * @return CSV produced according to the parsing result. Never {@code null}, maybe empty.
     */
    private String writeCSV(ParsingResult parsingResult) {
        if (parsingResult.isEmpty()) {
            return StringUtils.EMPTY;
        }
        var finalResult = new StringWriter();
        try (ICsvMapWriter csvWriter = new CsvMapWriter(finalResult, CsvPreference.EXCEL_PREFERENCE)) {
            csvWriter.writeHeader(parsingResult.getHeader());
            for (var aRow : parsingResult.getData()) {
                csvWriter.write(aRow, parsingResult.getHeader());
            }
        } catch (IOException e) {
            throw new RuntimeException("Unexpected IOException on String", e);
        }
        return finalResult.toString();
    }

    /**
     * Joins an array with forms data in CSV format and returns a merged CSV.
     *
     * @param data Array with forms data in CSV format. Each element has a header and 0 or more rows of a single form.
     * @return A CSV with all forms data merged. Never {@code null}, may be empty.
     */
    public String joinFormData(String[] data) {
        if (data == null || data.length == 0) {
            return StringUtils.EMPTY;
        }
        if (data.length == 1) {
            return data[0];
        }
        var parsingResult = parseCSVData(data);
        return writeCSV(parsingResult);
    }

    /**
     * A caseless representation of a String object.
     */
    final class CaselessString implements Comparable<CaselessString> {
        private final String string;
        private final String normalizedString;

        public CaselessString(String string) {
            this.string = string;
            this.normalizedString = string.toUpperCase();
        }

        @Override
        public boolean equals(Object obj) {
            if (!(obj instanceof CaselessString)) {
                return false;
            }
            return ((CaselessString) obj).normalizedString.equals(normalizedString);
        }

        @Override
        public int hashCode() {
            return normalizedString.hashCode();
        }

        @Override
        public int compareTo(CaselessString o) {
            return normalizedString.compareTo(o.normalizedString);
        }

        @Override
        public String toString() {
            return string;
        }
    }

    /**
     * Represents the parsing result of the forms data. It has the final header and the data.
     */
    class ParsingResult {
        private String[] header;
        private List<Map<String, String>> data;

        public ParsingResult() {
            // Empty result
        }

        public ParsingResult(List<CaselessString> header, List<Map<String, String>> data) {
            this.header = new String[header.size()];
            for (var i = 0; i < header.size(); i++) {
                this.header[i] = header.get(i).toString();
            }
            this.data = data;
        }

        public String[] getHeader() {
            return header;
        }

        public List<Map<String, String>> getData() {
            return data;
        }

        /**
         * Checks if the ParsingResult is empty.
         *
         * @return true if the ParsingResult object has no header and no data. False otherwise.
         */
        public boolean isEmpty() {
            return header == null && data == null;
        }
    }
}
