/*
 * Copyright 1999-2026 Percussion Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.percussion.server;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;

/**
 * Verifies the third-party copyright blurb emitted at server startup.
 *
 * <p>Policy (issue #1689): the resource-bundle text and root {@code NOTICE.txt} are a stable,
 * version-agnostic pointer only. The authoritative versioned inventory is build-generated by {@code
 * org.codehaus.mojo:license-maven-plugin} as {@code THIRD-PARTY.txt}. Do not reintroduce
 * hand-curated component lists or dependency version pins here.
 */
public class PSThirdPartyCopyrightTest {

  /** Matches {@code vMAJOR.MINOR.PATCH}-style pins (e.g. {@code v1.3.1}, {@code v2.3.232}). */
  private static final Pattern VERSION_PIN = Pattern.compile("\\bv\\d+\\.\\d+\\.\\d+\\b");

  /** Matches bare {@code MAJOR.MINOR.PATCH} pins (no leading {@code v}). */
  private static final Pattern BARE_VERSION_PIN =
      Pattern.compile("(?<!\\.)\\b\\d+\\.\\d+\\.\\d+\\b(?!\\.)");

  /** Microsoft SQL Server JDBC preview tags such as {@code 13.3.1.jre11-preview}. */
  private static final Pattern MS_JDBC_PREVIEW_TAG =
      Pattern.compile("\\d+\\.\\d+\\.\\d+\\.jre\\d+-preview");

  private static String thirdPartyCopyright() {
    ResourceBundle bundle =
        ResourceBundle.getBundle("com.percussion.server.PSStringResources", Locale.ROOT);
    String text = bundle.getString("thirdPartyCopyright");
    assertNotNull(text, "thirdPartyCopyright bundle key must be defined");
    return text;
  }

  @Test
  void bundleExposesNonEmptyThirdPartyCopyright() {
    assertFalse(thirdPartyCopyright().isBlank(), "thirdPartyCopyright must not be blank");
  }

  @Test
  void thirdPartyCopyrightIsStablePointerToGeneratedInventory() {
    String text = thirdPartyCopyright();
    assertTrue(
        text.contains("Apache License, Version 2.0"),
        "blurb should reference the product Apache 2.0 license");
    assertTrue(
        text.contains("Intersoft Data Labs"),
        "blurb should credit Intersoft Data Labs for ongoing maintenance");
    assertTrue(
        text.contains("THIRD-PARTY.txt"),
        "blurb must point at the build-generated THIRD-PARTY.txt inventory");
    assertTrue(
        text.contains("build time") || text.contains("generated from the Maven reactor"),
        "blurb should state that the inventory is build-generated");
  }

  @Test
  void thirdPartyCopyrightHasNoDependencyVersionPins() {
    String text = thirdPartyCopyright();
    assertFalse(
        VERSION_PIN.matcher(text).find(),
        "stable pointer must not contain 'vMAJOR.MINOR.PATCH' style version pins");
    assertFalse(
        BARE_VERSION_PIN.matcher(text).find(),
        "stable pointer must not contain bare 'MAJOR.MINOR.PATCH' style version pins");
    assertFalse(
        MS_JDBC_PREVIEW_TAG.matcher(text).find(),
        "stable pointer must not contain Microsoft SQL Server JDBC preview tags");
  }

  @Test
  void thirdPartyCopyrightDoesNotHandCurateComponentCatalog() {
    String text = thirdPartyCopyright();
    // Regression guard against the pre-#1689 hand-curated disclaimer style.
    assertFalse(
        text.contains("Lato font") || text.contains("SIL Open Font License"),
        "must not reintroduce dropped Lato / SIL OFL prose");
    assertFalse(
        text.contains("jTDS driver v") || text.contains("jTDS driver 1."),
        "must not pin jTDS (or any driver) versions in the startup blurb");
    assertFalse(
        text.contains("Bundled Apache and Apache-licensed components"),
        "must not hand-curate category component catalogs — the plugin inventory owns that");
    assertFalse(
        text.contains("Bundled JDBC drivers and relational persistence"),
        "must not hand-curate JDBC component catalogs — the plugin inventory owns that");
  }

  @Test
  void copyrightKeyCreditsIntersoftAndCurrentYearRange() {
    ResourceBundle bundle =
        ResourceBundle.getBundle("com.percussion.server.PSStringResources", Locale.ROOT);
    String text = bundle.getString("copyright");
    assertNotNull(text, "copyright bundle key must be defined");
    assertTrue(text.contains("1999-2026"), "copyright year range should include 2026");
    assertTrue(
        text.contains("Intersoft Data Labs"),
        "copyright should credit Intersoft Data Labs for ongoing maintenance");
  }

  @Test
  void noticeTxtIsStablePointerWithoutVersionPins() throws IOException {
    Path notice = resolveRepoRootNotice();
    assertTrue(Files.isRegularFile(notice), "NOTICE.txt must exist at repo root: " + notice);
    String text = Files.readString(notice, StandardCharsets.UTF_8);
    assertFalse(text.isBlank(), "NOTICE.txt must not be blank");
    assertTrue(
        text.contains("THIRD-PARTY.txt"),
        "NOTICE.txt must point at the build-generated THIRD-PARTY.txt inventory");
    assertTrue(
        text.contains("Apache License, Version 2.0"),
        "NOTICE.txt should reference the product Apache 2.0 license");
    assertFalse(
        VERSION_PIN.matcher(text).find() || BARE_VERSION_PIN.matcher(text).find(),
        "NOTICE.txt must not contain dependency version pins");
    assertFalse(
        text.contains("Lato font") || text.contains("jTDS driver"),
        "NOTICE.txt must not hand-curate third-party component lists");
  }

  /**
   * Resolves repo-root {@code NOTICE.txt} whether Surefire runs from {@code system/} or the reactor
   * root. Portable: uses {@link Path} resolve, not hardcoded separators.
   */
  private static Path resolveRepoRootNotice() {
    Path cwd = Paths.get("").toAbsolutePath().normalize();
    Path[] candidates =
        new Path[] {
          cwd.resolve("NOTICE.txt"),
          cwd.getParent() != null ? cwd.getParent().resolve("NOTICE.txt") : null,
          cwd.resolve("..").resolve("NOTICE.txt").normalize(),
        };
    for (Path candidate : candidates) {
      if (candidate != null && Files.isRegularFile(candidate)) {
        return candidate;
      }
    }
    // Last resort: walk up a few levels (worktrees / nested cwd).
    Path probe = cwd;
    for (int i = 0; i < 6 && probe != null; i++) {
      Path at = probe.resolve("NOTICE.txt");
      if (Files.isRegularFile(at)) {
        return at;
      }
      probe = probe.getParent();
    }
    return cwd.resolve("NOTICE.txt");
  }
}
