# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ release, development ]
  pull_request:
    branches: [ development ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | 
          echo "${{ secrets.SIGNING_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.SIGNING_KEYSTOREPASS }}" --batch release.keystore.asc > release.keystore
      - uses: actions/setup-java@v3
        with:
            java-version: '8'
            distribution: 'liberica'
      - uses: s4u/maven-settings-action@v2.8.0
        with:
            oracleRepo: true
            servers: |
                  [{
                      "id": "percussion.s3.repo",
                      "username": "${{ secrets.S3_MAVEN_USERNAME }}",
                      "password": "${{ secrets.S3_MAVEN_PASSWORD }}"
                  }]
            properties: '[ {"signing.keystoreFile": "${{secrets.SIGNING_KEYSTOREFILE}}"},{"signing.keystorePass": "${{secrets.SIGNING_KEYSTOREPASS}}"},{"signing.keystoreType": "${{secrets.SIGNING_KEYSTORE_TYPE}}"},{"signing.keystoreAlias": "${{secrets.SIGNING_KEYSTORE_ALIAS}}"},{"signing.keyPass": "${{secrets.SIGNING_KEY_PASS}}"}]'
      - run: mvn -B package --file pom.xml